const data = [
  {
    fullName: "Malachi Yeaman",
    gender: "Male",
    jobTitle: "Chemical Engineer",
    language: "Somali",
    ssn: "706-11-8802",
    money: "$555.39",
  },
  {
    fullName: "Phyllis Docwra",
    gender: "Female",
    jobTitle: "Senior Financial Analyst",
    language: "Zulu",
    ssn: "390-53-7722",
    money: "$761.50",
  },
  {
    fullName: "Delila Skipsey",
    gender: "Female",
    jobTitle: "Account Representative III",
    language: "Georgian",
    ssn: "422-48-7597",
    money: "$780.35",
  },
  {
    fullName: "Ransom Ivashkov",
    gender: "Male",
    jobTitle: "Human Resources Assistant IV",
    language: "Ndebele",
    ssn: "562-38-7084",
    money: "$354.02",
  },
  {
    fullName: "Leoline Knottley",
    gender: "Female",
    jobTitle: "Biostatistician III",
    language: "Fijian",
    ssn: "585-16-9805",
    money: "$22.68",
  },
  {
    fullName: "Ham Bettinson",
    gender: "Male",
    jobTitle: "Systems Administrator IV",
    language: "Montenegrin",
    ssn: "110-42-0619",
    money: "$996.03",
  },
  {
    fullName: "Edward Decroix",
    gender: "Male",
    jobTitle: "Physical Therapy Assistant",
    language: "French",
    ssn: "780-49-3260",
    money: "$542.69",
  },
  {
    fullName: "Marylin Kemwall",
    gender: "Female",
    jobTitle: "Structural Analysis Engineer",
    language: "Croatian",
    ssn: "354-23-5862",
    money: "$52.35",
  },
  {
    fullName: "Carlos MacAndreis",
    gender: "Male",
    jobTitle: "Staff Scientist",
    language: "Icelandic",
    ssn: "433-42-9277",
    money: "$962.27",
  },
  {
    fullName: "Tammara Byrd",
    gender: "Female",
    jobTitle: "Marketing Assistant",
    language: "Tswana",
    ssn: "760-58-9247",
    money: "$426.56",
  },
  {
    fullName: "Town Sansum",
    gender: "Male",
    jobTitle: "Project Manager",
    language: "Khmer",
    ssn: "766-69-7630",
    money: "$951.01",
  },
  {
    fullName: "Drusie Ilbert",
    gender: "Female",
    jobTitle: "Environmental Specialist",
    language: "Moldovan",
    ssn: "831-30-7804",
    money: "$24.65",
  },
  {
    fullName: "Findley Bonafacino",
    gender: "Male",
    jobTitle: "Health Coach IV",
    language: "Lithuanian",
    ssn: "658-66-6053",
    money: "$630.56",
  },
  {
    fullName: "Corby Belchem",
    gender: "Male",
    jobTitle: "Senior Sales Associate",
    language: "Malagasy",
    ssn: "858-46-2317",
    money: "$257.26",
  },
  {
    fullName: "Mal Pauluzzi",
    gender: "Male",
    jobTitle: "Analog Circuit Design manager",
    language: "Hiri Motu",
    ssn: "191-96-1325",
    money: "$57.51",
  },
  {
    fullName: "Marjory McCumesky",
    gender: "Female",
    jobTitle: "Help Desk Technician",
    language: "Hindi",
    ssn: "113-36-9077",
    money: "$517.11",
  },
  {
    fullName: "Hunter Probat",
    gender: "Male",
    jobTitle: "Sales Associate",
    language: "Belarusian",
    ssn: "411-31-2862",
    money: "$583.74",
  },
  {
    fullName: "Brit Angove",
    gender: "Male",
    jobTitle: "Nurse",
    language: "Persian",
    ssn: "844-03-5493",
    money: "$226.48",
  },
  {
    fullName: "Haleigh De Launde",
    gender: "Male",
    jobTitle: "Automation Specialist II",
    language: "Fijian",
    ssn: "497-80-5942",
    money: "$178.59",
  },
  {
    fullName: "Masha Kyndred",
    gender: "Female",
    jobTitle: "Mechanical Systems Engineer",
    language: "Indonesian",
    ssn: "146-75-4371",
    money: "$517.59",
  },
  {
    fullName: "Dunc Corley",
    gender: "Male",
    jobTitle: "Paralegal",
    language: "Luxembourgish",
    ssn: "430-67-2827",
    money: "$116.38",
  },
  {
    fullName: "Roddy Gosnell",
    gender: "Male",
    jobTitle: "Editor",
    language: "Georgian",
    ssn: "866-99-4570",
    money: "$904.64",
  },
  {
    fullName: "Loni Spera",
    gender: "Female",
    jobTitle: "Paralegal",
    language: "German",
    ssn: "413-76-2489",
    money: "$949.14",
  },
  {
    fullName: "Daisi Proud",
    gender: "Female",
    jobTitle: "Actuary",
    language: "Italian",
    ssn: "594-81-2316",
    money: "$273.24",
  },
  {
    fullName: "Hermon Smythin",
    gender: "Male",
    jobTitle: "Operator",
    language: "Assamese",
    ssn: "453-59-9607",
    money: "$424.51",
  },
  {
    fullName: "Ignazio McClay",
    gender: "Male",
    jobTitle: "Research Assistant III",
    language: "Telugu",
    ssn: "556-12-6884",
    money: "$845.44",
  },
  {
    fullName: "Johnny Berzin",
    gender: "Male",
    jobTitle: "Research Associate",
    language: "New Zealand Sign Language",
    ssn: "613-77-1287",
    money: "$866.85",
  },
  {
    fullName: "Idalia Piet",
    gender: "Female",
    jobTitle: "Financial Analyst",
    language: "Hindi",
    ssn: "415-49-6448",
    money: "$235.05",
  },
  {
    fullName: "Gradey Newall",
    gender: "Male",
    jobTitle: "General Manager",
    language: "Croatian",
    ssn: "360-96-9634",
    money: "$687.21",
  },
  {
    fullName: "Berget Bondesen",
    gender: "Female",
    jobTitle: "Assistant Professor",
    language: "Tetum",
    ssn: "861-22-7535",
    money: "$731.43",
  },
  {
    fullName: "Bo Milkeham",
    gender: "Male",
    jobTitle: "Account Executive",
    language: "Icelandic",
    ssn: "690-97-4195",
    money: "$793.34",
  },
  {
    fullName: "Roselia Tidswell",
    gender: "Female",
    jobTitle: "Developer II",
    language: "Malagasy",
    ssn: "127-46-3171",
    money: "$875.07",
  },
  {
    fullName: "Lib Gadney",
    gender: "Female",
    jobTitle: "Recruiter",
    language: "Māori",
    ssn: "489-64-2363",
    money: "$699.61",
  },
  {
    fullName: "Alejoa Keener",
    gender: "Male",
    jobTitle: "Paralegal",
    language: "Amharic",
    ssn: "528-48-3413",
    money: "$851.66",
  },
  {
    fullName: "Bernadene Aikett",
    gender: "Female",
    jobTitle: "Developer II",
    language: "West Frisian",
    ssn: "612-64-3894",
    money: "$291.53",
  },
  {
    fullName: "Blondell Ricard",
    gender: "Female",
    jobTitle: "Marketing Assistant",
    language: "Kannada",
    ssn: "766-68-4980",
    money: "$481.87",
  },
  {
    fullName: "Hunt Wallsworth",
    gender: "Male",
    jobTitle: "Desktop Support Technician",
    language: "Maltese",
    ssn: "366-12-3736",
    money: "$264.38",
  },
  {
    fullName: "Ichabod Sellick",
    gender: "Male",
    jobTitle: "Junior Executive",
    language: "Spanish",
    ssn: "660-81-1714",
    money: "$721.33",
  },
  {
    fullName: "Aldridge Hollyard",
    gender: "Male",
    jobTitle: "Software Test Engineer I",
    language: "Assamese",
    ssn: "824-91-8980",
    money: "$561.85",
  },
  {
    fullName: "Aarika Melmore",
    gender: "Female",
    jobTitle: "Staff Accountant II",
    language: "Afrikaans",
    ssn: "256-38-0614",
    money: "$171.40",
  },
  {
    fullName: "Agustin Lanfranconi",
    gender: "Male",
    jobTitle: "Research Nurse",
    language: "Kyrgyz",
    ssn: "311-01-7140",
    money: "$384.52",
  },
  {
    fullName: "Zitella Matei",
    gender: "Female",
    jobTitle: "Programmer Analyst IV",
    language: "Danish",
    ssn: "337-71-4726",
    money: "$586.92",
  },
  {
    fullName: "Ami Eles",
    gender: "Female",
    jobTitle: "Sales Representative",
    language: "Marathi",
    ssn: "244-56-9689",
    money: "$832.86",
  },
  {
    fullName: "Jessy Sumers",
    gender: "Female",
    jobTitle: "Software Test Engineer I",
    language: "Armenian",
    ssn: "758-63-5755",
    money: "$507.72",
  },
  {
    fullName: "Elset Malbon",
    gender: "Female",
    jobTitle: "Business Systems Development Analyst",
    language: "Afrikaans",
    ssn: "524-90-3289",
    money: "$946.87",
  },
  {
    fullName: "Fernanda Berick",
    gender: "Female",
    jobTitle: "Financial Analyst",
    language: "Amharic",
    ssn: "885-43-7443",
    money: "$638.81",
  },
  {
    fullName: "Rose Culwen",
    gender: "Female",
    jobTitle: "Media Manager II",
    language: "Gujarati",
    ssn: "218-50-5998",
    money: "$383.60",
  },
  {
    fullName: "Corbin Grishechkin",
    gender: "Male",
    jobTitle: "Systems Administrator III",
    language: "Irish Gaelic",
    ssn: "823-85-8424",
    money: "$492.43",
  },
  {
    fullName: "Yoshi Devereux",
    gender: "Female",
    jobTitle: "Food Chemist",
    language: "English",
    ssn: "851-86-9722",
    money: "$500.68",
  },
  {
    fullName: "Stephana Mitchinson",
    gender: "Female",
    jobTitle: "Research Nurse",
    language: "Czech",
    ssn: "729-63-1034",
    money: "$542.64",
  },
  {
    fullName: "Brett Blowfield",
    gender: "Male",
    jobTitle: "Account Representative III",
    language: "Zulu",
    ssn: "656-95-8256",
    money: "$567.03",
  },
  {
    fullName: "Archibaldo Whimpenny",
    gender: "Male",
    jobTitle: "Nurse",
    language: "Croatian",
    ssn: "133-66-1323",
    money: "$444.10",
  },
  {
    fullName: "Paco Cisco",
    gender: "Male",
    jobTitle: "Product Engineer",
    language: "Pashto",
    ssn: "878-87-1606",
    money: "$354.29",
  },
  {
    fullName: "Babs Readmire",
    gender: "Female",
    jobTitle: "Software Consultant",
    language: "Oriya",
    ssn: "824-86-8892",
    money: "$958.65",
  },
  {
    fullName: "Feodor Laimable",
    gender: "Male",
    jobTitle: "Project Manager",
    language: "Dutch",
    ssn: "438-05-5449",
    money: "$399.13",
  },
  {
    fullName: "Maurizia Joss",
    gender: "Female",
    jobTitle: "GIS Technical Architect",
    language: "Tswana",
    ssn: "325-04-9919",
    money: "$929.18",
  },
  {
    fullName: "Maybelle Alekseev",
    gender: "Female",
    jobTitle: "Sales Associate",
    language: "Maltese",
    ssn: "292-50-3218",
    money: "$327.67",
  },
  {
    fullName: "Rory Von Der Empten",
    gender: "Female",
    jobTitle: "Occupational Therapist",
    language: "Montenegrin",
    ssn: "727-97-2722",
    money: "$684.99",
  },
  {
    fullName: "Rachele Pady",
    gender: "Female",
    jobTitle: "Paralegal",
    language: "Korean",
    ssn: "216-58-0766",
    money: "$808.87",
  },
  {
    fullName: "Clyde Condell",
    gender: "Male",
    jobTitle: "Operator",
    language: "Kurdish",
    ssn: "602-70-0055",
    money: "$450.53",
  },
  {
    fullName: "Ralf Woodcraft",
    gender: "Male",
    jobTitle: "Quality Control Specialist",
    language: "Romanian",
    ssn: "745-70-9773",
    money: "$299.31",
  },
  {
    fullName: "Leonidas German",
    gender: "Male",
    jobTitle: "Health Coach III",
    language: "Luxembourgish",
    ssn: "896-50-1401",
    money: "$399.65",
  },
  {
    fullName: "Cissy Dyball",
    gender: "Female",
    jobTitle: "Graphic Designer",
    language: "Maltese",
    ssn: "442-69-7510",
    money: "$442.65",
  },
  {
    fullName: "Carmine Longhirst",
    gender: "Male",
    jobTitle: "Senior Cost Accountant",
    language: "Czech",
    ssn: "565-49-6720",
    money: "$111.35",
  },
  {
    fullName: "Hunt Venmore",
    gender: "Male",
    jobTitle: "Human Resources Assistant II",
    language: "Thai",
    ssn: "580-26-4372",
    money: "$917.07",
  },
  {
    fullName: "Brana Waggett",
    gender: "Female",
    jobTitle: "Community Outreach Specialist",
    language: "Czech",
    ssn: "524-26-1193",
    money: "$327.89",
  },
  {
    fullName: "Simeon Hartburn",
    gender: "Male",
    jobTitle: "Product Engineer",
    language: "Spanish",
    ssn: "145-65-8324",
    money: "$177.83",
  },
  {
    fullName: "Elwyn Tippetts",
    gender: "Male",
    jobTitle: "Web Developer III",
    language: "Tsonga",
    ssn: "867-02-3249",
    money: "$151.34",
  },
  {
    fullName: "Lucius Crutchley",
    gender: "Male",
    jobTitle: "Legal Assistant",
    language: "Greek",
    ssn: "317-92-6229",
    money: "$772.70",
  },
  {
    fullName: "Wiatt Batten",
    gender: "Male",
    jobTitle: "Speech Pathologist",
    language: "Romanian",
    ssn: "857-43-2772",
    money: "$235.65",
  },
  {
    fullName: "Hayyim Dacombe",
    gender: "Male",
    jobTitle: "Clinical Specialist",
    language: "Tamil",
    ssn: "112-24-2641",
    money: "$161.77",
  },
  {
    fullName: "Kendra Rodolf",
    gender: "Female",
    jobTitle: "Staff Accountant II",
    language: "Kurdish",
    ssn: "861-73-0820",
    money: "$875.16",
  },
  {
    fullName: "Rosemaria Bitten",
    gender: "Female",
    jobTitle: "Senior Developer",
    language: "Belarusian",
    ssn: "706-33-3671",
    money: "$720.03",
  },
  {
    fullName: "Bartholomeus Brister",
    gender: "Male",
    jobTitle: "Technical Writer",
    language: "Lithuanian",
    ssn: "534-40-2641",
    money: "$137.29",
  },
  {
    fullName: "Aryn Markussen",
    gender: "Female",
    jobTitle: "Engineer IV",
    language: "Malay",
    ssn: "213-15-6445",
    money: "$160.37",
  },
  {
    fullName: "Butch Andrzejak",
    gender: "Male",
    jobTitle: "GIS Technical Architect",
    language: "Irish Gaelic",
    ssn: "221-55-1130",
    money: "$34.73",
  },
  {
    fullName: "Bevon Syversen",
    gender: "Male",
    jobTitle: "Quality Control Specialist",
    language: "Korean",
    ssn: "404-25-4359",
    money: "$742.46",
  },
  {
    fullName: "Rourke Geator",
    gender: "Male",
    jobTitle: "Structural Engineer",
    language: "Zulu",
    ssn: "536-21-3577",
    money: "$478.31",
  },
  {
    fullName: "Prentiss Jurs",
    gender: "Male",
    jobTitle: "Operator",
    language: "Papiamento",
    ssn: "565-23-9321",
    money: "$946.03",
  },
  {
    fullName: "Creigh Laybourn",
    gender: "Male",
    jobTitle: "VP Accounting",
    language: "Dhivehi",
    ssn: "374-01-4342",
    money: "$893.14",
  },
  {
    fullName: "Garnette Sterte",
    gender: "Female",
    jobTitle: "Occupational Therapist",
    language: "Amharic",
    ssn: "822-59-0959",
    money: "$57.24",
  },
  {
    fullName: "Beckie Mart",
    gender: "Female",
    jobTitle: "Automation Specialist I",
    language: "Lao",
    ssn: "148-48-0280",
    money: "$898.77",
  },
  {
    fullName: "Mathew O'Hannigan",
    gender: "Male",
    jobTitle: "Health Coach I",
    language: "Gujarati",
    ssn: "713-97-7067",
    money: "$183.43",
  },
  {
    fullName: "Arthur Ridsdale",
    gender: "Male",
    jobTitle: "Biostatistician I",
    language: "Marathi",
    ssn: "629-52-7920",
    money: "$45.26",
  },
  {
    fullName: "Lurleen Hyndson",
    gender: "Female",
    jobTitle: "Internal Auditor",
    language: "Chinese",
    ssn: "511-52-4415",
    money: "$88.37",
  },
  {
    fullName: "Thomasin Trahear",
    gender: "Female",
    jobTitle: "Quality Engineer",
    language: "Gagauz",
    ssn: "195-40-8188",
    money: "$785.05",
  },
  {
    fullName: "Orazio McCaw",
    gender: "Male",
    jobTitle: "Senior Developer",
    language: "Dzongkha",
    ssn: "439-05-5384",
    money: "$378.25",
  },
  {
    fullName: "Dee Jermin",
    gender: "Female",
    jobTitle: "Internal Auditor",
    language: "Polish",
    ssn: "288-11-7389",
    money: "$139.41",
  },
  {
    fullName: "Hubert Trustrie",
    gender: "Male",
    jobTitle: "Data Coordinator",
    language: "Fijian",
    ssn: "205-77-0402",
    money: "$35.56",
  },
  {
    fullName: "Rozamond Conaghan",
    gender: "Female",
    jobTitle: "Structural Engineer",
    language: "Gagauz",
    ssn: "323-91-1118",
    money: "$133.38",
  },
  {
    fullName: "Christoph Vero",
    gender: "Male",
    jobTitle: "Research Nurse",
    language: "Gagauz",
    ssn: "308-93-2746",
    money: "$235.18",
  },
  {
    fullName: "Gawain Fleeming",
    gender: "Male",
    jobTitle: "Environmental Specialist",
    language: "Tswana",
    ssn: "577-33-4730",
    money: "$621.68",
  },
  {
    fullName: "Norah Noone",
    gender: "Female",
    jobTitle: "Financial Analyst",
    language: "Yiddish",
    ssn: "655-86-9168",
    money: "$558.40",
  },
  {
    fullName: "Skylar Sieghard",
    gender: "Male",
    jobTitle: "Executive Secretary",
    language: "Assamese",
    ssn: "426-63-8343",
    money: "$187.34",
  },
  {
    fullName: "Felisha Murkitt",
    gender: "Female",
    jobTitle: "VP Product Management",
    language: "Kannada",
    ssn: "164-26-8907",
    money: "$182.10",
  },
  {
    fullName: "Fabio Yewdell",
    gender: "Male",
    jobTitle: "Food Chemist",
    language: "Ndebele",
    ssn: "115-19-2174",
    money: "$31.10",
  },
  {
    fullName: "Claudetta Trembey",
    gender: "Female",
    jobTitle: "Human Resources Assistant I",
    language: "Dari",
    ssn: "542-98-9361",
    money: "$304.75",
  },
  {
    fullName: "Nanete Breem",
    gender: "Female",
    jobTitle: "Quality Engineer",
    language: "New Zealand Sign Language",
    ssn: "515-97-4743",
    money: "$763.48",
  },
  {
    fullName: "Missie Raynton",
    gender: "Female",
    jobTitle: "Web Developer IV",
    language: "Lithuanian",
    ssn: "876-44-2290",
    money: "$862.24",
  },
  {
    fullName: "Chicky Dafforne",
    gender: "Male",
    jobTitle: "Safety Technician IV",
    language: "Lao",
    ssn: "205-36-6368",
    money: "$380.03",
  },
  {
    fullName: "Roberta Pounds",
    gender: "Female",
    jobTitle: "Database Administrator II",
    language: "Hebrew",
    ssn: "699-74-2305",
    money: "$800.45",
  },
  {
    fullName: "Sheila Winman",
    gender: "Female",
    jobTitle: "Social Worker",
    language: "Aymara",
    ssn: "214-99-2925",
    money: "$891.72",
  },
  {
    fullName: "Cathryn Han",
    gender: "Female",
    jobTitle: "Project Manager",
    language: "Tok Pisin",
    ssn: "672-08-2056",
    money: "$637.90",
  },
  {
    fullName: "Kally Rupel",
    gender: "Female",
    jobTitle: "Engineer IV",
    language: "West Frisian",
    ssn: "363-40-3763",
    money: "$225.11",
  },
  {
    fullName: "Graeme Lutman",
    gender: "Male",
    jobTitle: "Electrical Engineer",
    language: "Dutch",
    ssn: "675-14-7694",
    money: "$504.53",
  },
  {
    fullName: "Lavina Mettetal",
    gender: "Female",
    jobTitle: "Sales Associate",
    language: "Moldovan",
    ssn: "796-44-6282",
    money: "$287.64",
  },
  {
    fullName: "Dex Dowderswell",
    gender: "Male",
    jobTitle: "Data Coordinator",
    language: "Albanian",
    ssn: "263-68-5881",
    money: "$109.64",
  },
  {
    fullName: "Nadine Tomaello",
    gender: "Female",
    jobTitle: "Registered Nurse",
    language: "Dutch",
    ssn: "205-68-8002",
    money: "$806.80",
  },
  {
    fullName: "Lionel Bream",
    gender: "Male",
    jobTitle: "Database Administrator II",
    language: "Estonian",
    ssn: "301-48-2147",
    money: "$978.33",
  },
  {
    fullName: "Reamonn Romanelli",
    gender: "Male",
    jobTitle: "Teacher",
    language: "Sotho",
    ssn: "506-25-5328",
    money: "$829.89",
  },
  {
    fullName: "Jyoti Southwood",
    gender: "Female",
    jobTitle: "Administrative Assistant I",
    language: "Czech",
    ssn: "257-75-8140",
    money: "$270.31",
  },
  {
    fullName: "Debor Wharby",
    gender: "Female",
    jobTitle: "Budget/Accounting Analyst II",
    language: "Estonian",
    ssn: "727-13-5842",
    money: "$538.41",
  },
  {
    fullName: "Walt Chisnall",
    gender: "Male",
    jobTitle: "Tax Accountant",
    language: "Kyrgyz",
    ssn: "723-94-6465",
    money: "$570.85",
  },
  {
    fullName: "Reamonn Layfield",
    gender: "Male",
    jobTitle: "Tax Accountant",
    language: "Dari",
    ssn: "735-16-7767",
    money: "$739.32",
  },
  {
    fullName: "Renee Abbis",
    gender: "Female",
    jobTitle: "Dental Hygienist",
    language: "Tamil",
    ssn: "214-44-8289",
    money: "$996.39",
  },
  {
    fullName: "Bartel Keays",
    gender: "Male",
    jobTitle: "Paralegal",
    language: "Hiri Motu",
    ssn: "514-11-8300",
    money: "$155.06",
  },
  {
    fullName: "Dallon Hellmore",
    gender: "Male",
    jobTitle: "Marketing Manager",
    language: "Sotho",
    ssn: "673-94-9680",
    money: "$192.57",
  },
  {
    fullName: "Frederico Rosnau",
    gender: "Male",
    jobTitle: "Research Associate",
    language: "Zulu",
    ssn: "456-43-9925",
    money: "$156.41",
  },
  {
    fullName: "Gabriella Bewlay",
    gender: "Female",
    jobTitle: "Assistant Manager",
    language: "Latvian",
    ssn: "329-78-6154",
    money: "$211.29",
  },
  {
    fullName: "Arabella Reap",
    gender: "Female",
    jobTitle: "Senior Quality Engineer",
    language: "Kazakh",
    ssn: "139-40-4610",
    money: "$758.80",
  },
  {
    fullName: "Farleigh Steuart",
    gender: "Male",
    jobTitle: "Accountant IV",
    language: "Filipino",
    ssn: "458-66-6881",
    money: "$159.62",
  },
  {
    fullName: "Maurits Everil",
    gender: "Male",
    jobTitle: "Nurse Practicioner",
    language: "Sotho",
    ssn: "823-57-7191",
    money: "$561.75",
  },
  {
    fullName: "Micheal Blowing",
    gender: "Male",
    jobTitle: "Human Resources Manager",
    language: "Tok Pisin",
    ssn: "345-19-8804",
    money: "$956.66",
  },
  {
    fullName: "Bobbette Chapleo",
    gender: "Female",
    jobTitle: "Assistant Manager",
    language: "Chinese",
    ssn: "106-60-9169",
    money: "$544.41",
  },
  {
    fullName: "Aliza Pattington",
    gender: "Female",
    jobTitle: "Statistician III",
    language: "Persian",
    ssn: "152-02-1566",
    money: "$507.53",
  },
  {
    fullName: "Kacey Strangeways",
    gender: "Female",
    jobTitle: "Registered Nurse",
    language: "Icelandic",
    ssn: "522-76-6677",
    money: "$151.72",
  },
  {
    fullName: "Revkah Trahmel",
    gender: "Female",
    jobTitle: "Technical Writer",
    language: "Montenegrin",
    ssn: "201-99-0938",
    money: "$83.75",
  },
  {
    fullName: "Mufinella MacAndrew",
    gender: "Female",
    jobTitle: "Assistant Media Planner",
    language: "Papiamento",
    ssn: "159-73-5743",
    money: "$732.74",
  },
  {
    fullName: "Felipa Eirwin",
    gender: "Female",
    jobTitle: "Associate Professor",
    language: "Swahili",
    ssn: "301-37-7287",
    money: "$665.15",
  },
  {
    fullName: "Darill Aitken",
    gender: "Male",
    jobTitle: "Structural Engineer",
    language: "Punjabi",
    ssn: "655-23-1538",
    money: "$598.99",
  },
  {
    fullName: "Michal Phillot",
    gender: "Female",
    jobTitle: "Technical Writer",
    language: "Montenegrin",
    ssn: "671-78-5666",
    money: "$391.51",
  },
  {
    fullName: "Rosina Maskew",
    gender: "Female",
    jobTitle: "Information Systems Manager",
    language: "Pashto",
    ssn: "752-82-4946",
    money: "$854.57",
  },
  {
    fullName: "Millie Skettles",
    gender: "Female",
    jobTitle: "Chief Design Engineer",
    language: "Telugu",
    ssn: "802-05-3438",
    money: "$568.86",
  },
  {
    fullName: "Modesta Tarr",
    gender: "Female",
    jobTitle: "Marketing Assistant",
    language: "Albanian",
    ssn: "708-82-8236",
    money: "$480.41",
  },
  {
    fullName: "Rafaellle Boffey",
    gender: "Male",
    jobTitle: "Software Consultant",
    language: "Moldovan",
    ssn: "775-68-7052",
    money: "$958.91",
  },
  {
    fullName: "Aretha Sprowle",
    gender: "Female",
    jobTitle: "Mechanical Systems Engineer",
    language: "Pashto",
    ssn: "661-39-5699",
    money: "$106.84",
  },
  {
    fullName: "Hershel Nappin",
    gender: "Male",
    jobTitle: "VP Quality Control",
    language: "Hindi",
    ssn: "516-28-4191",
    money: "$553.77",
  },
  {
    fullName: "Cecilio Ohlsen",
    gender: "Male",
    jobTitle: "GIS Technical Architect",
    language: "Kashmiri",
    ssn: "621-53-7699",
    money: "$606.55",
  },
  {
    fullName: "Dionysus Jebb",
    gender: "Male",
    jobTitle: "Nuclear Power Engineer",
    language: "Punjabi",
    ssn: "499-24-3646",
    money: "$592.06",
  },
  {
    fullName: "Trix Sparwell",
    gender: "Female",
    jobTitle: "Human Resources Assistant II",
    language: "Latvian",
    ssn: "673-39-7679",
    money: "$384.24",
  },
  {
    fullName: "Andrea Lamperti",
    gender: "Male",
    jobTitle: "Sales Representative",
    language: "Czech",
    ssn: "511-84-1237",
    money: "$648.89",
  },
  {
    fullName: "Mace Disley",
    gender: "Male",
    jobTitle: "Associate Professor",
    language: "Macedonian",
    ssn: "816-67-1425",
    money: "$536.43",
  },
  {
    fullName: "Nollie Rigmond",
    gender: "Male",
    jobTitle: "Developer II",
    language: "Burmese",
    ssn: "665-32-2155",
    money: "$955.83",
  },
  {
    fullName: "Brandy Kettoe",
    gender: "Female",
    jobTitle: "Quality Engineer",
    language: "Spanish",
    ssn: "184-85-6755",
    money: "$734.15",
  },
  {
    fullName: "Drusie Fludgate",
    gender: "Female",
    jobTitle: "Nurse Practicioner",
    language: "Filipino",
    ssn: "846-98-7578",
    money: "$249.44",
  },
  {
    fullName: "Rina Glusby",
    gender: "Female",
    jobTitle: "Tax Accountant",
    language: "Telugu",
    ssn: "374-63-0703",
    money: "$305.74",
  },
  {
    fullName: "Dilly Dury",
    gender: "Male",
    jobTitle: "Senior Editor",
    language: "Bulgarian",
    ssn: "561-42-4337",
    money: "$974.86",
  },
  {
    fullName: "Gregg Quested",
    gender: "Male",
    jobTitle: "Account Executive",
    language: "Spanish",
    ssn: "750-46-9954",
    money: "$693.54",
  },
  {
    fullName: "Barnabas Yurkov",
    gender: "Male",
    jobTitle: "Nurse Practicioner",
    language: "Finnish",
    ssn: "643-10-8132",
    money: "$778.50",
  },
  {
    fullName: "Brandice Stratz",
    gender: "Female",
    jobTitle: "Junior Executive",
    language: "Lao",
    ssn: "592-34-4973",
    money: "$577.00",
  },
  {
    fullName: "Lotty Manderson",
    gender: "Female",
    jobTitle: "Senior Financial Analyst",
    language: "Bislama",
    ssn: "542-16-5144",
    money: "$720.96",
  },
  {
    fullName: "Marrissa Yurchishin",
    gender: "Female",
    jobTitle: "Business Systems Development Analyst",
    language: "Aymara",
    ssn: "618-14-9737",
    money: "$29.31",
  },
  {
    fullName: "Shanna Fridlington",
    gender: "Female",
    jobTitle: "Project Manager",
    language: "Gagauz",
    ssn: "671-26-6970",
    money: "$46.58",
  },
  {
    fullName: "Reggy Scranedge",
    gender: "Male",
    jobTitle: "Civil Engineer",
    language: "Finnish",
    ssn: "371-60-0594",
    money: "$868.74",
  },
  {
    fullName: "Cookie Nolda",
    gender: "Female",
    jobTitle: "Accounting Assistant I",
    language: "Finnish",
    ssn: "689-44-5151",
    money: "$163.07",
  },
  {
    fullName: "Trixie Pescott",
    gender: "Female",
    jobTitle: "Biostatistician IV",
    language: "Kannada",
    ssn: "806-71-5092",
    money: "$958.97",
  },
  {
    fullName: "Dorella Taynton",
    gender: "Female",
    jobTitle: "Research Nurse",
    language: "Tamil",
    ssn: "294-67-1705",
    money: "$255.86",
  },
  {
    fullName: "Donia Petracchi",
    gender: "Female",
    jobTitle: "Programmer III",
    language: "Kazakh",
    ssn: "215-04-6477",
    money: "$636.71",
  },
  {
    fullName: "Caddric Caldero",
    gender: "Male",
    jobTitle: "VP Quality Control",
    language: "New Zealand Sign Language",
    ssn: "188-49-4751",
    money: "$177.81",
  },
  {
    fullName: "Odele Tumilson",
    gender: "Female",
    jobTitle: "Chief Design Engineer",
    language: "Macedonian",
    ssn: "138-76-6904",
    money: "$971.76",
  },
  {
    fullName: "Mace Larter",
    gender: "Male",
    jobTitle: "Librarian",
    language: "Georgian",
    ssn: "117-50-3344",
    money: "$409.15",
  },
  {
    fullName: "Asher Samways",
    gender: "Male",
    jobTitle: "VP Quality Control",
    language: "Malayalam",
    ssn: "789-02-0401",
    money: "$87.97",
  },
  {
    fullName: "Meggy Dyter",
    gender: "Female",
    jobTitle: "Internal Auditor",
    language: "Tetum",
    ssn: "481-91-0118",
    money: "$371.95",
  },
  {
    fullName: "Nicholle Raddenbury",
    gender: "Female",
    jobTitle: "Senior Financial Analyst",
    language: "Kashmiri",
    ssn: "427-87-7005",
    money: "$437.40",
  },
  {
    fullName: "Lemmy Saltrese",
    gender: "Male",
    jobTitle: "VP Product Management",
    language: "Mongolian",
    ssn: "390-12-6559",
    money: "$194.23",
  },
  {
    fullName: "Oran Stickford",
    gender: "Male",
    jobTitle: "Community Outreach Specialist",
    language: "Kurdish",
    ssn: "730-83-7526",
    money: "$16.04",
  },
  {
    fullName: "Nahum Lewisham",
    gender: "Male",
    jobTitle: "Safety Technician IV",
    language: "Lao",
    ssn: "409-89-2065",
    money: "$522.97",
  },
  {
    fullName: "Meade Plane",
    gender: "Female",
    jobTitle: "Systems Administrator IV",
    language: "Punjabi",
    ssn: "231-97-9738",
    money: "$875.32",
  },
  {
    fullName: "Heidi Sturror",
    gender: "Female",
    jobTitle: "Accounting Assistant II",
    language: "Tok Pisin",
    ssn: "212-10-2741",
    money: "$140.46",
  },
  {
    fullName: "Stephannie Yousef",
    gender: "Female",
    jobTitle: "VP Marketing",
    language: "Quechua",
    ssn: "484-61-5063",
    money: "$542.46",
  },
  {
    fullName: "Zsazsa Ransfield",
    gender: "Female",
    jobTitle: "Recruiter",
    language: "Lithuanian",
    ssn: "158-99-1389",
    money: "$651.46",
  },
  {
    fullName: "Vilma ducarme",
    gender: "Female",
    jobTitle: "Structural Engineer",
    language: "Dutch",
    ssn: "286-26-1820",
    money: "$49.19",
  },
  {
    fullName: "Duffie Tunkin",
    gender: "Male",
    jobTitle: "Technical Writer",
    language: "French",
    ssn: "529-80-4699",
    money: "$659.55",
  },
  {
    fullName: "Ella Vallance",
    gender: "Female",
    jobTitle: "Accountant II",
    language: "Amharic",
    ssn: "315-31-1007",
    money: "$385.56",
  },
  {
    fullName: "Ivie Walls",
    gender: "Female",
    jobTitle: "Professor",
    language: "Hindi",
    ssn: "628-26-0239",
    money: "$151.58",
  },
  {
    fullName: "Deeanne Bracegirdle",
    gender: "Female",
    jobTitle: "Help Desk Operator",
    language: "Kurdish",
    ssn: "556-24-4081",
    money: "$464.55",
  },
  {
    fullName: "Barnaby Blondin",
    gender: "Male",
    jobTitle: "Assistant Professor",
    language: "Gujarati",
    ssn: "166-44-6050",
    money: "$426.16",
  },
  {
    fullName: "Manfred Abade",
    gender: "Male",
    jobTitle: "VP Product Management",
    language: "Spanish",
    ssn: "662-53-2668",
    money: "$850.15",
  },
  {
    fullName: "Margaret Shevlin",
    gender: "Female",
    jobTitle: "Software Consultant",
    language: "Gujarati",
    ssn: "354-48-2990",
    money: "$271.36",
  },
  {
    fullName: "Reamonn Morter",
    gender: "Male",
    jobTitle: "Operator",
    language: "Danish",
    ssn: "899-99-0890",
    money: "$794.75",
  },
  {
    fullName: "Saunders Richel",
    gender: "Male",
    jobTitle: "Software Engineer III",
    language: "Kannada",
    ssn: "769-99-9701",
    money: "$331.95",
  },
  {
    fullName: "Neysa Langer",
    gender: "Female",
    jobTitle: "Technical Writer",
    language: "Kurdish",
    ssn: "880-07-7389",
    money: "$479.54",
  },
  {
    fullName: "Christos Mc Grath",
    gender: "Male",
    jobTitle: "Social Worker",
    language: "Danish",
    ssn: "512-10-5064",
    money: "$91.91",
  },
  {
    fullName: "Royall Skipperbottom",
    gender: "Male",
    jobTitle: "Sales Associate",
    language: "Telugu",
    ssn: "440-16-6281",
    money: "$889.75",
  },
  {
    fullName: "Karoly Rizzelli",
    gender: "Male",
    jobTitle: "Administrative Officer",
    language: "Irish Gaelic",
    ssn: "251-16-3865",
    money: "$889.96",
  },
  {
    fullName: "Jesse Wybourne",
    gender: "Female",
    jobTitle: "Automation Specialist III",
    language: "Azeri",
    ssn: "545-35-5978",
    money: "$506.18",
  },
  {
    fullName: "Ardeen Hendrikse",
    gender: "Female",
    jobTitle: "Database Administrator IV",
    language: "New Zealand Sign Language",
    ssn: "637-95-2855",
    money: "$198.55",
  },
  {
    fullName: "Maribeth Yuille",
    gender: "Female",
    jobTitle: "Research Assistant IV",
    language: "Czech",
    ssn: "239-95-8671",
    money: "$928.01",
  },
  {
    fullName: "Mari Glasby",
    gender: "Female",
    jobTitle: "Teacher",
    language: "Danish",
    ssn: "508-50-5449",
    money: "$50.77",
  },
  {
    fullName: "Wash Harkins",
    gender: "Male",
    jobTitle: "Director of Sales",
    language: "Hungarian",
    ssn: "835-13-2435",
    money: "$565.70",
  },
  {
    fullName: "Giff Pyvis",
    gender: "Male",
    jobTitle: "Engineer IV",
    language: "Zulu",
    ssn: "862-65-7512",
    money: "$694.85",
  },
  {
    fullName: "Marshall Whear",
    gender: "Male",
    jobTitle: "Quality Control Specialist",
    language: "Telugu",
    ssn: "715-67-7756",
    money: "$571.71",
  },
  {
    fullName: "Nicholle Milton-White",
    gender: "Female",
    jobTitle: "Sales Associate",
    language: "Montenegrin",
    ssn: "832-69-4090",
    money: "$446.78",
  },
  {
    fullName: "Gretal Westbrook",
    gender: "Female",
    jobTitle: "Associate Professor",
    language: "Lao",
    ssn: "398-34-5337",
    money: "$406.50",
  },
  {
    fullName: "Mercy Munkley",
    gender: "Female",
    jobTitle: "Registered Nurse",
    language: "Portuguese",
    ssn: "365-27-8904",
    money: "$526.06",
  },
  {
    fullName: "Loella Scorer",
    gender: "Female",
    jobTitle: "Project Manager",
    language: "Filipino",
    ssn: "129-14-9988",
    money: "$280.04",
  },
  {
    fullName: "Lily Hartegan",
    gender: "Female",
    jobTitle: "GIS Technical Architect",
    language: "Danish",
    ssn: "273-93-8806",
    money: "$186.88",
  },
  {
    fullName: "Elianore Stuckley",
    gender: "Female",
    jobTitle: "Programmer Analyst II",
    language: "Croatian",
    ssn: "609-25-9544",
    money: "$361.05",
  },
  {
    fullName: "Kenn Atton",
    gender: "Male",
    jobTitle: "Software Test Engineer III",
    language: "Korean",
    ssn: "730-38-4679",
    money: "$93.28",
  },
  {
    fullName: "Angelique Ouldred",
    gender: "Female",
    jobTitle: "Financial Advisor",
    language: "Malagasy",
    ssn: "851-83-2123",
    money: "$548.45",
  },
  {
    fullName: "Donn Henner",
    gender: "Male",
    jobTitle: "Account Executive",
    language: "Dutch",
    ssn: "122-40-8730",
    money: "$801.60",
  },
  {
    fullName: "Hadlee Vye",
    gender: "Male",
    jobTitle: "Community Outreach Specialist",
    language: "Malayalam",
    ssn: "329-73-8439",
    money: "$320.65",
  },
  {
    fullName: "Jojo Brownsword",
    gender: "Female",
    jobTitle: "Speech Pathologist",
    language: "Catalan",
    ssn: "251-11-4165",
    money: "$494.89",
  },
  {
    fullName: "Quill Daniele",
    gender: "Male",
    jobTitle: "Marketing Assistant",
    language: "Malayalam",
    ssn: "862-22-2535",
    money: "$784.85",
  },
  {
    fullName: "Tate Broggio",
    gender: "Male",
    jobTitle: "Accountant I",
    language: "Ndebele",
    ssn: "616-44-2796",
    money: "$295.83",
  },
  {
    fullName: "Gun Cudby",
    gender: "Male",
    jobTitle: "Web Designer I",
    language: "Hebrew",
    ssn: "619-64-3071",
    money: "$369.32",
  },
  {
    fullName: "Bert Bettenay",
    gender: "Female",
    jobTitle: "Executive Secretary",
    language: "French",
    ssn: "251-74-4948",
    money: "$783.82",
  },
  {
    fullName: "Ebony Deboo",
    gender: "Female",
    jobTitle: "Food Chemist",
    language: "Sotho",
    ssn: "144-94-3120",
    money: "$133.84",
  },
  {
    fullName: "Faith Twine",
    gender: "Female",
    jobTitle: "Research Assistant I",
    language: "Somali",
    ssn: "159-02-5937",
    money: "$357.46",
  },
  {
    fullName: "Norman Dimmack",
    gender: "Male",
    jobTitle: "Business Systems Development Analyst",
    language: "Lao",
    ssn: "633-20-6447",
    money: "$46.03",
  },
  {
    fullName: "Marline Fernely",
    gender: "Female",
    jobTitle: "Executive Secretary",
    language: "Bosnian",
    ssn: "767-93-5369",
    money: "$376.95",
  },
  {
    fullName: "Hewie Oboy",
    gender: "Male",
    jobTitle: "Assistant Professor",
    language: "Tsonga",
    ssn: "657-33-4776",
    money: "$665.66",
  },
  {
    fullName: "Lombard Murrow",
    gender: "Male",
    jobTitle: "Analog Circuit Design manager",
    language: "Japanese",
    ssn: "391-88-9003",
    money: "$333.02",
  },
  {
    fullName: "Mic Youson",
    gender: "Male",
    jobTitle: "Web Developer I",
    language: "Italian",
    ssn: "657-63-2693",
    money: "$549.68",
  },
  {
    fullName: "Demetris Selly",
    gender: "Male",
    jobTitle: "Senior Cost Accountant",
    language: "Armenian",
    ssn: "592-81-0125",
    money: "$836.98",
  },
  {
    fullName: "Clementina Tappor",
    gender: "Female",
    jobTitle: "Analyst Programmer",
    language: "Dari",
    ssn: "472-71-7654",
    money: "$927.17",
  },
  {
    fullName: "Amerigo Henrot",
    gender: "Male",
    jobTitle: "Research Nurse",
    language: "Malay",
    ssn: "189-49-6572",
    money: "$105.95",
  },
  {
    fullName: "Tony Gracey",
    gender: "Female",
    jobTitle: "Food Chemist",
    language: "Hindi",
    ssn: "568-93-0417",
    money: "$634.12",
  },
  {
    fullName: "Jenna Newnham",
    gender: "Female",
    jobTitle: "Actuary",
    language: "New Zealand Sign Language",
    ssn: "196-93-7214",
    money: "$206.71",
  },
  {
    fullName: "Bartlett Mault",
    gender: "Male",
    jobTitle: "Media Manager III",
    language: "Guaraní",
    ssn: "488-78-9404",
    money: "$985.88",
  },
  {
    fullName: "Camilla Gheorghe",
    gender: "Female",
    jobTitle: "Administrative Assistant IV",
    language: "French",
    ssn: "213-49-0988",
    money: "$285.56",
  },
  {
    fullName: "Olimpia Chang",
    gender: "Female",
    jobTitle: "Project Manager",
    language: "Norwegian",
    ssn: "694-26-2662",
    money: "$366.60",
  },
  {
    fullName: "Feliks Wildt",
    gender: "Male",
    jobTitle: "Operator",
    language: "Croatian",
    ssn: "811-48-1235",
    money: "$694.01",
  },
  {
    fullName: "Phip Tomaello",
    gender: "Male",
    jobTitle: "VP Marketing",
    language: "Korean",
    ssn: "676-68-2510",
    money: "$86.36",
  },
  {
    fullName: "Sidoney Cowdry",
    gender: "Female",
    jobTitle: "Director of Sales",
    language: "Luxembourgish",
    ssn: "487-20-8798",
    money: "$754.87",
  },
  {
    fullName: "Shani Benkhe",
    gender: "Female",
    jobTitle: "Analog Circuit Design manager",
    language: "Romanian",
    ssn: "346-68-4702",
    money: "$283.30",
  },
  {
    fullName: "Hersch Boichat",
    gender: "Male",
    jobTitle: "Statistician III",
    language: "Bosnian",
    ssn: "730-92-0403",
    money: "$996.61",
  },
  {
    fullName: "Alexandrina Firpi",
    gender: "Female",
    jobTitle: "Biostatistician I",
    language: "Tok Pisin",
    ssn: "398-28-7014",
    money: "$535.57",
  },
  {
    fullName: "Merl Dowry",
    gender: "Female",
    jobTitle: "Account Executive",
    language: "Northern Sotho",
    ssn: "205-68-0728",
    money: "$332.15",
  },
  {
    fullName: "Ambros Hollidge",
    gender: "Male",
    jobTitle: "Physical Therapy Assistant",
    language: "Swahili",
    ssn: "537-75-5844",
    money: "$765.63",
  },
  {
    fullName: "Janot Mowle",
    gender: "Female",
    jobTitle: "Graphic Designer",
    language: "Sotho",
    ssn: "811-63-5205",
    money: "$187.01",
  },
  {
    fullName: "Reinhold Keech",
    gender: "Male",
    jobTitle: "Actuary",
    language: "Swahili",
    ssn: "856-24-8730",
    money: "$125.26",
  },
  {
    fullName: "Alonso Brunsen",
    gender: "Male",
    jobTitle: "Community Outreach Specialist",
    language: "Malagasy",
    ssn: "851-09-6734",
    money: "$281.27",
  },
  {
    fullName: "Bari Roswarn",
    gender: "Female",
    jobTitle: "VP Sales",
    language: "Kannada",
    ssn: "525-60-9394",
    money: "$194.53",
  },
  {
    fullName: "Kaja Labrom",
    gender: "Female",
    jobTitle: "VP Accounting",
    language: "Belarusian",
    ssn: "116-47-8323",
    money: "$326.77",
  },
  {
    fullName: "Tamar Tessier",
    gender: "Female",
    jobTitle: "Senior Quality Engineer",
    language: "Italian",
    ssn: "185-40-7333",
    money: "$533.16",
  },
  {
    fullName: "Nester Curdell",
    gender: "Male",
    jobTitle: "Software Consultant",
    language: "German",
    ssn: "505-08-8201",
    money: "$647.51",
  },
  {
    fullName: "Friedrich Salzburger",
    gender: "Male",
    jobTitle: "Dental Hygienist",
    language: "Kannada",
    ssn: "882-07-9100",
    money: "$456.42",
  },
  {
    fullName: "Janis Mustoe",
    gender: "Female",
    jobTitle: "Chief Design Engineer",
    language: "Kurdish",
    ssn: "462-43-3892",
    money: "$393.66",
  },
  {
    fullName: "Hardy Stenet",
    gender: "Male",
    jobTitle: "Programmer IV",
    language: "Tamil",
    ssn: "163-68-4855",
    money: "$340.06",
  },
  {
    fullName: "Algernon McDirmid",
    gender: "Male",
    jobTitle: "Structural Engineer",
    language: "Kyrgyz",
    ssn: "431-87-3107",
    money: "$12.75",
  },
  {
    fullName: "Tamera Walder",
    gender: "Female",
    jobTitle: "Teacher",
    language: "Hebrew",
    ssn: "872-71-3922",
    money: "$147.58",
  },
  {
    fullName: "Yorke Bernli",
    gender: "Male",
    jobTitle: "Electrical Engineer",
    language: "Assamese",
    ssn: "442-27-0997",
    money: "$859.04",
  },
  {
    fullName: "Filberte Harkes",
    gender: "Male",
    jobTitle: "Senior Quality Engineer",
    language: "Montenegrin",
    ssn: "640-49-0399",
    money: "$816.00",
  },
  {
    fullName: "Godart Wootton",
    gender: "Male",
    jobTitle: "Account Executive",
    language: "French",
    ssn: "648-99-4555",
    money: "$236.64",
  },
  {
    fullName: "Munroe Ragate",
    gender: "Male",
    jobTitle: "GIS Technical Architect",
    language: "Montenegrin",
    ssn: "648-97-7905",
    money: "$264.98",
  },
  {
    fullName: "Hill McLarens",
    gender: "Male",
    jobTitle: "Software Consultant",
    language: "Guaraní",
    ssn: "806-83-3797",
    money: "$31.78",
  },
  {
    fullName: "Nikolas Rosgen",
    gender: "Male",
    jobTitle: "Office Assistant III",
    language: "Bislama",
    ssn: "576-35-8598",
    money: "$773.74",
  },
  {
    fullName: "Teddi Fussen",
    gender: "Female",
    jobTitle: "Accountant I",
    language: "Pashto",
    ssn: "327-70-5043",
    money: "$272.53",
  },
  {
    fullName: "Neall Yosifov",
    gender: "Male",
    jobTitle: "Teacher",
    language: "Arabic",
    ssn: "705-45-1194",
    money: "$628.91",
  },
  {
    fullName: "Edythe Sever",
    gender: "Female",
    jobTitle: "Business Systems Development Analyst",
    language: "Italian",
    ssn: "222-73-1231",
    money: "$963.76",
  },
  {
    fullName: "Lynett Dockery",
    gender: "Female",
    jobTitle: "Data Coordinator",
    language: "Croatian",
    ssn: "502-36-2386",
    money: "$680.94",
  },
  {
    fullName: "Aguistin Oscroft",
    gender: "Male",
    jobTitle: "Food Chemist",
    language: "Swedish",
    ssn: "515-45-3657",
    money: "$537.57",
  },
  {
    fullName: "Sonja Davidofski",
    gender: "Female",
    jobTitle: "Product Engineer",
    language: "English",
    ssn: "340-65-6246",
    money: "$787.47",
  },
  {
    fullName: "De MacAllaster",
    gender: "Female",
    jobTitle: "Teacher",
    language: "Swahili",
    ssn: "740-58-2030",
    money: "$84.40",
  },
  {
    fullName: "Brade Guiton",
    gender: "Male",
    jobTitle: "Programmer I",
    language: "Hungarian",
    ssn: "467-49-1486",
    money: "$790.67",
  },
  {
    fullName: "Mathilda Findlater",
    gender: "Female",
    jobTitle: "Junior Executive",
    language: "New Zealand Sign Language",
    ssn: "817-05-1081",
    money: "$487.92",
  },
  {
    fullName: "Jean Segoe",
    gender: "Female",
    jobTitle: "Librarian",
    language: "Albanian",
    ssn: "219-85-3845",
    money: "$640.91",
  },
  {
    fullName: "Nealy Minard",
    gender: "Male",
    jobTitle: "Environmental Tech",
    language: "Dzongkha",
    ssn: "200-90-0033",
    money: "$118.57",
  },
  {
    fullName: "Alejandrina Rockwill",
    gender: "Female",
    jobTitle: "Assistant Manager",
    language: "French",
    ssn: "621-48-1827",
    money: "$660.84",
  },
  {
    fullName: "Nye Champney",
    gender: "Male",
    jobTitle: "Senior Financial Analyst",
    language: "Tajik",
    ssn: "499-47-2331",
    money: "$429.56",
  },
  {
    fullName: "Garner O'Tuohy",
    gender: "Male",
    jobTitle: "Database Administrator IV",
    language: "Filipino",
    ssn: "712-86-0804",
    money: "$349.30",
  },
  {
    fullName: "Ethyl Denford",
    gender: "Female",
    jobTitle: "Associate Professor",
    language: "Maltese",
    ssn: "874-01-9054",
    money: "$884.01",
  },
  {
    fullName: "Larine Mollison",
    gender: "Female",
    jobTitle: "Developer II",
    language: "Kyrgyz",
    ssn: "455-82-1181",
    money: "$250.39",
  },
  {
    fullName: "Isaak Pelerin",
    gender: "Male",
    jobTitle: "Staff Accountant II",
    language: "Macedonian",
    ssn: "187-21-0485",
    money: "$337.84",
  },
  {
    fullName: "Trula Bielfeldt",
    gender: "Female",
    jobTitle: "Assistant Manager",
    language: "Afrikaans",
    ssn: "508-21-8476",
    money: "$280.67",
  },
  {
    fullName: "Constanta Mutch",
    gender: "Female",
    jobTitle: "Environmental Tech",
    language: "Albanian",
    ssn: "520-68-9446",
    money: "$778.16",
  },
  {
    fullName: "Billi Castagnier",
    gender: "Female",
    jobTitle: "Research Assistant I",
    language: "Tetum",
    ssn: "542-17-1239",
    money: "$983.63",
  },
  {
    fullName: "Roxie Frensch",
    gender: "Female",
    jobTitle: "Senior Financial Analyst",
    language: "Burmese",
    ssn: "728-73-5039",
    money: "$853.59",
  },
  {
    fullName: "Katharyn Inkster",
    gender: "Female",
    jobTitle: "Project Manager",
    language: "Japanese",
    ssn: "686-98-4805",
    money: "$782.30",
  },
  {
    fullName: "Turner Pagett",
    gender: "Male",
    jobTitle: "Editor",
    language: "English",
    ssn: "670-67-9115",
    money: "$501.44",
  },
  {
    fullName: "Cleveland Simmon",
    gender: "Male",
    jobTitle: "Staff Accountant III",
    language: "Chinese",
    ssn: "137-87-2302",
    money: "$452.99",
  },
  {
    fullName: "Grantley Waldren",
    gender: "Male",
    jobTitle: "Safety Technician III",
    language: "Kannada",
    ssn: "606-44-2228",
    money: "$376.04",
  },
  {
    fullName: "Waneta Heales",
    gender: "Female",
    jobTitle: "Administrative Officer",
    language: "Luxembourgish",
    ssn: "142-28-5617",
    money: "$25.75",
  },
  {
    fullName: "Peirce Wilshin",
    gender: "Male",
    jobTitle: "Administrative Officer",
    language: "Japanese",
    ssn: "147-81-4465",
    money: "$53.33",
  },
  {
    fullName: "Adrien Cropper",
    gender: "Male",
    jobTitle: "Nurse Practicioner",
    language: "Romanian",
    ssn: "235-56-9025",
    money: "$674.93",
  },
  {
    fullName: "Aimil Cuardall",
    gender: "Female",
    jobTitle: "VP Marketing",
    language: "Malayalam",
    ssn: "760-60-0344",
    money: "$69.33",
  },
  {
    fullName: "Rourke McGillivrie",
    gender: "Male",
    jobTitle: "Product Engineer",
    language: "Persian",
    ssn: "171-22-3241",
    money: "$708.04",
  },
  {
    fullName: "Beniamino Seagar",
    gender: "Male",
    jobTitle: "Professor",
    language: "West Frisian",
    ssn: "383-24-7086",
    money: "$347.26",
  },
  {
    fullName: "Ag Kiossel",
    gender: "Female",
    jobTitle: "Marketing Manager",
    language: "Fijian",
    ssn: "461-39-9181",
    money: "$550.76",
  },
  {
    fullName: "Even Horlock",
    gender: "Male",
    jobTitle: "Office Assistant III",
    language: "Kurdish",
    ssn: "717-98-4409",
    money: "$653.15",
  },
  {
    fullName: "Doyle Graffin",
    gender: "Male",
    jobTitle: "Software Test Engineer IV",
    language: "Somali",
    ssn: "699-78-2776",
    money: "$133.27",
  },
  {
    fullName: "Lucie Casterou",
    gender: "Female",
    jobTitle: "Senior Financial Analyst",
    language: "Italian",
    ssn: "321-06-0973",
    money: "$273.37",
  },
  {
    fullName: "Alex Bubeer",
    gender: "Male",
    jobTitle: "VP Product Management",
    language: "Icelandic",
    ssn: "874-15-0676",
    money: "$619.36",
  },
  {
    fullName: "Constanta Jouanny",
    gender: "Female",
    jobTitle: "Nuclear Power Engineer",
    language: "Dutch",
    ssn: "102-52-0955",
    money: "$41.02",
  },
  {
    fullName: "Teri Olland",
    gender: "Female",
    jobTitle: "Account Representative I",
    language: "Japanese",
    ssn: "831-97-1756",
    money: "$957.78",
  },
  {
    fullName: "Gavra Dalgarnocht",
    gender: "Female",
    jobTitle: "Legal Assistant",
    language: "Maltese",
    ssn: "391-99-6912",
    money: "$666.41",
  },
  {
    fullName: "Daveen Dalligan",
    gender: "Female",
    jobTitle: "Administrative Assistant I",
    language: "Amharic",
    ssn: "559-89-1794",
    money: "$451.07",
  },
  {
    fullName: "Callean Copestick",
    gender: "Male",
    jobTitle: "Business Systems Development Analyst",
    language: "Filipino",
    ssn: "192-14-7288",
    money: "$826.94",
  },
  {
    fullName: "Gordan Humblestone",
    gender: "Male",
    jobTitle: "Computer Systems Analyst I",
    language: "Malayalam",
    ssn: "406-45-0649",
    money: "$686.81",
  },
  {
    fullName: "Morganica MacBain",
    gender: "Female",
    jobTitle: "Accounting Assistant II",
    language: "Georgian",
    ssn: "796-57-9634",
    money: "$869.91",
  },
  {
    fullName: "Micheal Kinsella",
    gender: "Male",
    jobTitle: "Occupational Therapist",
    language: "Sotho",
    ssn: "622-87-4655",
    money: "$823.41",
  },
  {
    fullName: "Pepillo Butler",
    gender: "Male",
    jobTitle: "Registered Nurse",
    language: "Icelandic",
    ssn: "662-02-2537",
    money: "$53.24",
  },
  {
    fullName: "Mozes Mussen",
    gender: "Male",
    jobTitle: "Financial Advisor",
    language: "Kyrgyz",
    ssn: "279-67-4637",
    money: "$714.81",
  },
  {
    fullName: "Orland Merrifield",
    gender: "Male",
    jobTitle: "Nurse",
    language: "Amharic",
    ssn: "849-67-1549",
    money: "$358.59",
  },
  {
    fullName: "Jennica Ruslen",
    gender: "Female",
    jobTitle: "Product Engineer",
    language: "Northern Sotho",
    ssn: "642-21-4823",
    money: "$655.10",
  },
  {
    fullName: "Florenza Scamadin",
    gender: "Female",
    jobTitle: "Financial Analyst",
    language: "Persian",
    ssn: "501-34-3753",
    money: "$989.08",
  },
  {
    fullName: "Howard Howieson",
    gender: "Male",
    jobTitle: "Senior Developer",
    language: "Hiri Motu",
    ssn: "521-13-0097",
    money: "$427.78",
  },
  {
    fullName: "Missy Keller",
    gender: "Female",
    jobTitle: "Senior Editor",
    language: "Hindi",
    ssn: "680-10-2017",
    money: "$60.48",
  },
  {
    fullName: "Esra Speere",
    gender: "Male",
    jobTitle: "Web Designer II",
    language: "Macedonian",
    ssn: "671-61-0374",
    money: "$510.10",
  },
];

// 1. 성별이 남성이고 직업(jobTitle)이 Engineer가 포함된 사람들만 나타내기!

const q1 = data.filter(
  (x) => x.gender == "Male" && x.jobTitle.includes("Engineer")
);

console.log(q1);

// 2. 이름에서 가족이름을 없애고, ssn을 하이픈 없애고, money를 달러에서 원화로 환율 적용시킨 후 나타내기!

const q2 = data.map((x) => {
  x.fullName = x.fullName.split(" ")[0];
  x.ssn = x.ssn.split("-").reduce((a, c) => a + c);
  x.money = +x.money.slice(1) * 1470;

  return x;
});

console.log(q2);
