const data = [
  {
    fullName: "Joe Hedlestone",
    gender: "Male",
    jobTitle: "Sales Representative",
    language: "Bulgarian",
    ssn: "886-78-0406",
    money: "$337.31",
  },
  {
    fullName: "Bartram Leggott",
    gender: "Male",
    jobTitle: "Director of Sales",
    language: "Armenian",
    ssn: "424-98-7818",
    money: "$95.04",
  },
  {
    fullName: "Melvin Gaggen",
    gender: "Male",
    jobTitle: "Staff Accountant IV",
    language: "Japanese",
    ssn: "607-88-5758",
    money: "$314.46",
  },
  {
    fullName: "Anderson Tatem",
    gender: "Male",
    jobTitle: "Account Representative II",
    language: "Bislama",
    ssn: "785-35-7296",
    money: "$323.04",
  },
  {
    fullName: "Blancha Ballam",
    gender: "Female",
    jobTitle: "Human Resources Assistant III",
    language: "Hungarian",
    ssn: "695-25-8789",
    money: "$4.24",
  },
  {
    fullName: "Chelsie Hainge",
    gender: "Female",
    jobTitle: "Research Associate",
    language: "Catalan",
    ssn: "825-10-3111",
    money: "$159.95",
  },
  {
    fullName: "Janie Goult",
    gender: "Female",
    jobTitle: "Marketing Assistant",
    language: "Kannada",
    ssn: "606-96-1349",
    money: "$841.01",
  },
  {
    fullName: "Larissa Torri",
    gender: "Female",
    jobTitle: "Payment Adjustment Coordinator",
    language: "Malayalam",
    ssn: "689-15-1294",
    money: "$296.47",
  },
  {
    fullName: "Nichole Graben",
    gender: "Female",
    jobTitle: "Electrical Engineer",
    language: "Tamil",
    ssn: "875-06-7969",
    money: "$419.78",
  },
  {
    fullName: "Billy Twycross",
    gender: "Female",
    jobTitle: "Quality Engineer",
    language: "Dhivehi",
    ssn: "133-81-3823",
    money: "$902.25",
  },
  {
    fullName: "Shaine Snary",
    gender: "Male",
    jobTitle: "Graphic Designer",
    language: "Telugu",
    ssn: "425-24-0040",
    money: "$841.98",
  },
  {
    fullName: "Engelbert Bucktharp",
    gender: "Male",
    jobTitle: "Sales Representative",
    language: "Fijian",
    ssn: "753-52-1394",
    money: "$525.21",
  },
  {
    fullName: "Michelina Carhart",
    gender: "Female",
    jobTitle: "Budget/Accounting Analyst IV",
    language: "Tsonga",
    ssn: "810-35-6944",
    money: "$936.70",
  },
  {
    fullName: "Halli Viel",
    gender: "Female",
    jobTitle: "Structural Engineer",
    language: "Tok Pisin",
    ssn: "454-29-0545",
    money: "$258.20",
  },
  {
    fullName: "Pip Hutcheons",
    gender: "Male",
    jobTitle: "VP Marketing",
    language: "Khmer",
    ssn: "283-75-8169",
    money: "$26.13",
  },
  {
    fullName: "Bruce Palethorpe",
    gender: "Male",
    jobTitle: "Occupational Therapist",
    language: "Czech",
    ssn: "778-63-5964",
    money: "$180.91",
  },
  {
    fullName: "Tillie Kermeen",
    gender: "Female",
    jobTitle: "Tax Accountant",
    language: "Kannada",
    ssn: "397-44-2220",
    money: "$279.09",
  },
  {
    fullName: "Christiana Broun",
    gender: "Female",
    jobTitle: "Help Desk Operator",
    language: "Punjabi",
    ssn: "466-38-6368",
    money: "$882.12",
  },
  {
    fullName: "Xerxes Andor",
    gender: "Male",
    jobTitle: "Environmental Tech",
    language: "Burmese",
    ssn: "876-36-6447",
    money: "$552.49",
  },
  {
    fullName: "Siegfried Worvell",
    gender: "Male",
    jobTitle: "Director of Sales",
    language: "Malayalam",
    ssn: "144-80-5497",
    money: "$116.32",
  },
  {
    fullName: "Alon Rathjen",
    gender: "Male",
    jobTitle: "Actuary",
    language: "Norwegian",
    ssn: "181-44-7531",
    money: "$782.46",
  },
  {
    fullName: "Lew Hynd",
    gender: "Male",
    jobTitle: "Budget/Accounting Analyst II",
    language: "Papiamento",
    ssn: "102-53-2965",
    money: "$916.16",
  },
  {
    fullName: "Jodi Luigi",
    gender: "Male",
    jobTitle: "Design Engineer",
    language: "Pashto",
    ssn: "616-52-9764",
    money: "$834.72",
  },
  {
    fullName: "Gothart Deverock",
    gender: "Male",
    jobTitle: "Food Chemist",
    language: "Swati",
    ssn: "490-63-1051",
    money: "$123.69",
  },
  {
    fullName: "Wilbert Schusterl",
    gender: "Male",
    jobTitle: "Assistant Professor",
    language: "Azeri",
    ssn: "663-33-9185",
    money: "$822.37",
  },
  {
    fullName: "Maxine Donaway",
    gender: "Female",
    jobTitle: "Quality Engineer",
    language: "Swahili",
    ssn: "262-20-8764",
    money: "$920.34",
  },
  {
    fullName: "Kania Wrankmore",
    gender: "Female",
    jobTitle: "Legal Assistant",
    language: "Estonian",
    ssn: "424-33-0265",
    money: "$168.86",
  },
  {
    fullName: "Ram Wolledge",
    gender: "Male",
    jobTitle: "Accountant I",
    language: "Gagauz",
    ssn: "892-74-5950",
    money: "$239.53",
  },
  {
    fullName: "Yorke Cosins",
    gender: "Male",
    jobTitle: "Accountant I",
    language: "Swedish",
    ssn: "697-77-0047",
    money: "$596.50",
  },
  {
    fullName: "Bealle Abbet",
    gender: "Male",
    jobTitle: "Internal Auditor",
    language: "Khmer",
    ssn: "614-48-3075",
    money: "$644.03",
  },
  {
    fullName: "North Battin",
    gender: "Male",
    jobTitle: "Database Administrator IV",
    language: "Portuguese",
    ssn: "846-35-0382",
    money: "$622.34",
  },
  {
    fullName: "Marissa Fasler",
    gender: "Female",
    jobTitle: "Programmer III",
    language: "Estonian",
    ssn: "536-45-0256",
    money: "$601.19",
  },
  {
    fullName: "Dominga Sherlaw",
    gender: "Female",
    jobTitle: "Account Executive",
    language: "Swahili",
    ssn: "896-90-8792",
    money: "$865.12",
  },
  {
    fullName: "Millisent Collett",
    gender: "Female",
    jobTitle: "Design Engineer",
    language: "German",
    ssn: "375-44-8028",
    money: "$315.59",
  },
  {
    fullName: "Forrester Cowper",
    gender: "Male",
    jobTitle: "Pharmacist",
    language: "Mongolian",
    ssn: "383-18-8023",
    money: "$459.14",
  },
  {
    fullName: "Becky Icom",
    gender: "Female",
    jobTitle: "Clinical Specialist",
    language: "Latvian",
    ssn: "544-72-7519",
    money: "$198.64",
  },
  {
    fullName: "Simmonds Dumbarton",
    gender: "Male",
    jobTitle: "Executive Secretary",
    language: "Thai",
    ssn: "236-26-5042",
    money: "$852.22",
  },
  {
    fullName: "Barr Eckery",
    gender: "Male",
    jobTitle: "Civil Engineer",
    language: "Dhivehi",
    ssn: "193-07-1774",
    money: "$133.46",
  },
  {
    fullName: "Elwood Corfield",
    gender: "Male",
    jobTitle: "Accounting Assistant II",
    language: "Hiri Motu",
    ssn: "196-88-9846",
    money: "$597.58",
  },
  {
    fullName: "Stafani Shallcroff",
    gender: "Female",
    jobTitle: "Systems Administrator III",
    language: "Montenegrin",
    ssn: "716-31-4834",
    money: "$440.53",
  },
  {
    fullName: "Missy Chadwen",
    gender: "Female",
    jobTitle: "Account Representative IV",
    language: "Pashto",
    ssn: "306-05-1830",
    money: "$797.21",
  },
  {
    fullName: "Karia Grimmett",
    gender: "Female",
    jobTitle: "Editor",
    language: "Belarusian",
    ssn: "219-11-9700",
    money: "$925.46",
  },
  {
    fullName: "Jessalyn Barwood",
    gender: "Female",
    jobTitle: "Operator",
    language: "Montenegrin",
    ssn: "487-97-5711",
    money: "$147.85",
  },
  {
    fullName: "Cornall Leadbitter",
    gender: "Male",
    jobTitle: "Structural Analysis Engineer",
    language: "Somali",
    ssn: "394-37-2809",
    money: "$62.88",
  },
  {
    fullName: "Delora Down",
    gender: "Female",
    jobTitle: "VP Accounting",
    language: "Dzongkha",
    ssn: "629-21-4634",
    money: "$874.28",
  },
  {
    fullName: "Chris Ringe",
    gender: "Female",
    jobTitle: "Software Consultant",
    language: "West Frisian",
    ssn: "878-79-3326",
    money: "$26.08",
  },
  {
    fullName: "Burty Rumming",
    gender: "Male",
    jobTitle: "Senior Editor",
    language: "Nepali",
    ssn: "638-07-0493",
    money: "$925.64",
  },
  {
    fullName: "Linc Barkshire",
    gender: "Male",
    jobTitle: "Desktop Support Technician",
    language: "French",
    ssn: "401-55-8030",
    money: "$264.79",
  },
  {
    fullName: "Pierre Whife",
    gender: "Male",
    jobTitle: "Sales Representative",
    language: "Quechua",
    ssn: "829-96-9694",
    money: "$322.35",
  },
  {
    fullName: "Ignace Offord",
    gender: "Male",
    jobTitle: "Senior Cost Accountant",
    language: "Bislama",
    ssn: "790-30-3591",
    money: "$370.75",
  },
  {
    fullName: "Curtice Grishanin",
    gender: "Male",
    jobTitle: "Web Developer I",
    language: "Lithuanian",
    ssn: "506-02-6961",
    money: "$215.67",
  },
  {
    fullName: "Henri Veivers",
    gender: "Male",
    jobTitle: "Legal Assistant",
    language: "Czech",
    ssn: "294-05-8645",
    money: "$708.41",
  },
  {
    fullName: "Sharla Bolstridge",
    gender: "Female",
    jobTitle: "Programmer II",
    language: "Gujarati",
    ssn: "126-68-1601",
    money: "$606.36",
  },
  {
    fullName: "Robers Mullane",
    gender: "Male",
    jobTitle: "Speech Pathologist",
    language: "Bulgarian",
    ssn: "428-67-7036",
    money: "$14.39",
  },
  {
    fullName: "Tracy Mussard",
    gender: "Female",
    jobTitle: "Analyst Programmer",
    language: "Korean",
    ssn: "854-44-2340",
    money: "$676.74",
  },
  {
    fullName: "Gabriell Blazy",
    gender: "Female",
    jobTitle: "General Manager",
    language: "Amharic",
    ssn: "333-82-6471",
    money: "$383.33",
  },
  {
    fullName: "Karoly Berthel",
    gender: "Female",
    jobTitle: "Research Associate",
    language: "Hebrew",
    ssn: "229-17-1276",
    money: "$970.44",
  },
  {
    fullName: "Ricki Okroy",
    gender: "Male",
    jobTitle: "Editor",
    language: "Afrikaans",
    ssn: "152-49-2454",
    money: "$909.75",
  },
  {
    fullName: "Maegan Dellenty",
    gender: "Female",
    jobTitle: "Quality Engineer",
    language: "Yiddish",
    ssn: "815-98-1536",
    money: "$26.92",
  },
  {
    fullName: "Stefanie Wyne",
    gender: "Female",
    jobTitle: "Product Engineer",
    language: "Maltese",
    ssn: "854-53-9176",
    money: "$174.64",
  },
  {
    fullName: "Emmi Kilsby",
    gender: "Female",
    jobTitle: "Senior Developer",
    language: "Norwegian",
    ssn: "604-98-5953",
    money: "$286.63",
  },
  {
    fullName: "Reynolds Lippini",
    gender: "Male",
    jobTitle: "Administrative Assistant I",
    language: "Amharic",
    ssn: "496-81-7816",
    money: "$463.79",
  },
  {
    fullName: "Karon Scini",
    gender: "Female",
    jobTitle: "Quality Engineer",
    language: "Czech",
    ssn: "356-59-6184",
    money: "$150.67",
  },
  {
    fullName: "Corney Topp",
    gender: "Male",
    jobTitle: "Assistant Professor",
    language: "Hiri Motu",
    ssn: "837-76-6288",
    money: "$754.11",
  },
  {
    fullName: "Lilly Baton",
    gender: "Female",
    jobTitle: "Web Developer I",
    language: "Indonesian",
    ssn: "450-63-3147",
    money: "$845.68",
  },
  {
    fullName: "Tommy Carnell",
    gender: "Female",
    jobTitle: "Senior Quality Engineer",
    language: "Hindi",
    ssn: "795-29-1681",
    money: "$297.29",
  },
  {
    fullName: "Margie Wishart",
    gender: "Female",
    jobTitle: "Recruiter",
    language: "Irish Gaelic",
    ssn: "402-31-4005",
    money: "$927.85",
  },
  {
    fullName: "Elwira French",
    gender: "Female",
    jobTitle: "Web Developer II",
    language: "Romanian",
    ssn: "550-39-5282",
    money: "$349.79",
  },
  {
    fullName: "Aleece Garrigan",
    gender: "Female",
    jobTitle: "Quality Engineer",
    language: "Nepali",
    ssn: "783-01-5974",
    money: "$212.00",
  },
  {
    fullName: "Philippe Housden",
    gender: "Female",
    jobTitle: "Community Outreach Specialist",
    language: "Afrikaans",
    ssn: "729-19-4167",
    money: "$964.52",
  },
  {
    fullName: "Nara Georgievski",
    gender: "Female",
    jobTitle: "Software Test Engineer IV",
    language: "Malayalam",
    ssn: "200-09-0754",
    money: "$426.99",
  },
  {
    fullName: "Olia Shelbourne",
    gender: "Female",
    jobTitle: "Speech Pathologist",
    language: "English",
    ssn: "229-05-0441",
    money: "$202.79",
  },
  {
    fullName: "Ruprecht Yurocjhin",
    gender: "Male",
    jobTitle: "Social Worker",
    language: "Malagasy",
    ssn: "510-14-9250",
    money: "$701.97",
  },
  {
    fullName: "Peggi Makey",
    gender: "Female",
    jobTitle: "Mechanical Systems Engineer",
    language: "Telugu",
    ssn: "417-01-3281",
    money: "$597.44",
  },
  {
    fullName: "Corinne Tousey",
    gender: "Female",
    jobTitle: "Operator",
    language: "Lao",
    ssn: "200-52-9408",
    money: "$498.42",
  },
  {
    fullName: "Osmund Masham",
    gender: "Male",
    jobTitle: "Analyst Programmer",
    language: "Hindi",
    ssn: "845-53-8722",
    money: "$460.62",
  },
  {
    fullName: "Latrena Volette",
    gender: "Female",
    jobTitle: "Assistant Manager",
    language: "Swati",
    ssn: "286-39-7954",
    money: "$876.68",
  },
  {
    fullName: "Wynne Bront",
    gender: "Female",
    jobTitle: "Systems Administrator IV",
    language: "Greek",
    ssn: "720-72-4596",
    money: "$271.56",
  },
  {
    fullName: "Felizio Dowles",
    gender: "Male",
    jobTitle: "Senior Developer",
    language: "Quechua",
    ssn: "281-45-8140",
    money: "$848.48",
  },
  {
    fullName: "Don McMillan",
    gender: "Male",
    jobTitle: "Help Desk Operator",
    language: "Armenian",
    ssn: "515-42-8922",
    money: "$79.63",
  },
  {
    fullName: "Javier Fevers",
    gender: "Male",
    jobTitle: "Compensation Analyst",
    language: "Haitian Creole",
    ssn: "197-41-5552",
    money: "$61.59",
  },
  {
    fullName: "Denis Eakly",
    gender: "Male",
    jobTitle: "Structural Engineer",
    language: "Hiri Motu",
    ssn: "397-83-1413",
    money: "$542.45",
  },
  {
    fullName: "Standford Hillatt",
    gender: "Male",
    jobTitle: "Assistant Professor",
    language: "Khmer",
    ssn: "194-05-1413",
    money: "$232.02",
  },
  {
    fullName: "Karine Chill",
    gender: "Female",
    jobTitle: "Recruiter",
    language: "Malay",
    ssn: "826-12-0706",
    money: "$144.23",
  },
  {
    fullName: "Von Ackwood",
    gender: "Male",
    jobTitle: "Geological Engineer",
    language: "Mongolian",
    ssn: "171-79-2211",
    money: "$931.31",
  },
  {
    fullName: "Lucais MacAughtrie",
    gender: "Male",
    jobTitle: "Office Assistant I",
    language: "Tsonga",
    ssn: "236-46-7588",
    money: "$688.89",
  },
  {
    fullName: "Halette Marcq",
    gender: "Female",
    jobTitle: "Engineer II",
    language: "Irish Gaelic",
    ssn: "449-46-3307",
    money: "$825.34",
  },
  {
    fullName: "Rozanna Blything",
    gender: "Female",
    jobTitle: "Geologist IV",
    language: "Punjabi",
    ssn: "675-47-2637",
    money: "$657.90",
  },
  {
    fullName: "Monah Avo",
    gender: "Female",
    jobTitle: "Associate Professor",
    language: "Marathi",
    ssn: "754-99-6901",
    money: "$863.56",
  },
  {
    fullName: "Emmery McNellis",
    gender: "Male",
    jobTitle: "Programmer Analyst II",
    language: "Montenegrin",
    ssn: "409-40-4672",
    money: "$693.73",
  },
  {
    fullName: "Elka Giocannoni",
    gender: "Female",
    jobTitle: "Structural Analysis Engineer",
    language: "Gagauz",
    ssn: "245-91-1564",
    money: "$777.85",
  },
  {
    fullName: "Kenna Sole",
    gender: "Female",
    jobTitle: "Staff Accountant I",
    language: "Korean",
    ssn: "240-35-7275",
    money: "$316.20",
  },
  {
    fullName: "Garry Rolingson",
    gender: "Male",
    jobTitle: "Dental Hygienist",
    language: "Gujarati",
    ssn: "470-01-6433",
    money: "$446.54",
  },
  {
    fullName: "Anne-marie Greenman",
    gender: "Female",
    jobTitle: "Pharmacist",
    language: "Yiddish",
    ssn: "608-22-5611",
    money: "$933.91",
  },
  {
    fullName: "Alayne Kenzie",
    gender: "Female",
    jobTitle: "Programmer III",
    language: "German",
    ssn: "700-90-8051",
    money: "$707.68",
  },
  {
    fullName: "Clarie McCourtie",
    gender: "Female",
    jobTitle: "General Manager",
    language: "Finnish",
    ssn: "716-24-1935",
    money: "$650.28",
  },
  {
    fullName: "Bradford Le febre",
    gender: "Male",
    jobTitle: "Speech Pathologist",
    language: "Marathi",
    ssn: "606-35-6479",
    money: "$839.05",
  },
  {
    fullName: "Allina Hurling",
    gender: "Female",
    jobTitle: "Help Desk Technician",
    language: "Croatian",
    ssn: "302-18-4260",
    money: "$43.97",
  },
  {
    fullName: "Philly Byers",
    gender: "Female",
    jobTitle: "Community Outreach Specialist",
    language: "German",
    ssn: "531-80-6520",
    money: "$686.60",
  },
  {
    fullName: "Enrichetta McCane",
    gender: "Female",
    jobTitle: "Statistician I",
    language: "Assamese",
    ssn: "462-56-1135",
    money: "$557.34",
  },
  {
    fullName: "Melba Haig",
    gender: "Female",
    jobTitle: "Analyst Programmer",
    language: "Khmer",
    ssn: "662-69-0579",
    money: "$403.74",
  },
  {
    fullName: "Britte Pic",
    gender: "Female",
    jobTitle: "VP Accounting",
    language: "Northern Sotho",
    ssn: "171-78-8964",
    money: "$40.14",
  },
  {
    fullName: "Marianna Slayford",
    gender: "Female",
    jobTitle: "Environmental Specialist",
    language: "Kurdish",
    ssn: "574-80-1328",
    money: "$400.98",
  },
  {
    fullName: "Kerry Sharpous",
    gender: "Female",
    jobTitle: "Registered Nurse",
    language: "Kannada",
    ssn: "261-49-8772",
    money: "$985.28",
  },
  {
    fullName: "Gayelord Anderbrugge",
    gender: "Male",
    jobTitle: "Assistant Manager",
    language: "Kyrgyz",
    ssn: "116-93-9892",
    money: "$809.14",
  },
  {
    fullName: "Candis Biskupiak",
    gender: "Female",
    jobTitle: "Safety Technician II",
    language: "Tok Pisin",
    ssn: "564-08-9753",
    money: "$422.00",
  },
  {
    fullName: "Halley Dressel",
    gender: "Female",
    jobTitle: "Director of Sales",
    language: "Finnish",
    ssn: "486-78-8578",
    money: "$889.30",
  },
  {
    fullName: "Garrot Price",
    gender: "Male",
    jobTitle: "Payment Adjustment Coordinator",
    language: "Tetum",
    ssn: "847-88-4667",
    money: "$77.74",
  },
  {
    fullName: "Nicole Dance",
    gender: "Female",
    jobTitle: "Graphic Designer",
    language: "Khmer",
    ssn: "566-24-4016",
    money: "$133.61",
  },
  {
    fullName: "Genvieve Yurchenko",
    gender: "Female",
    jobTitle: "Programmer I",
    language: "Latvian",
    ssn: "340-82-9958",
    money: "$660.13",
  },
  {
    fullName: "Xylina Grubb",
    gender: "Female",
    jobTitle: "Database Administrator II",
    language: "Arabic",
    ssn: "187-08-2872",
    money: "$78.56",
  },
  {
    fullName: "Ulrike Burman",
    gender: "Female",
    jobTitle: "Research Nurse",
    language: "Malay",
    ssn: "584-49-6794",
    money: "$245.05",
  },
  {
    fullName: "Clerissa Ghidetti",
    gender: "Female",
    jobTitle: "Graphic Designer",
    language: "Māori",
    ssn: "484-40-7648",
    money: "$733.73",
  },
  {
    fullName: "Morly Shackell",
    gender: "Male",
    jobTitle: "Chief Design Engineer",
    language: "Amharic",
    ssn: "776-82-5187",
    money: "$168.26",
  },
  {
    fullName: "Amalie Kareman",
    gender: "Female",
    jobTitle: "Technical Writer",
    language: "New Zealand Sign Language",
    ssn: "862-58-6599",
    money: "$598.08",
  },
  {
    fullName: "Natale Scamadin",
    gender: "Male",
    jobTitle: "Pharmacist",
    language: "Moldovan",
    ssn: "894-82-0032",
    money: "$839.70",
  },
  {
    fullName: "Elwood Polon",
    gender: "Male",
    jobTitle: "Paralegal",
    language: "Norwegian",
    ssn: "369-74-0749",
    money: "$947.91",
  },
  {
    fullName: "Drusi Winterbotham",
    gender: "Female",
    jobTitle: "Community Outreach Specialist",
    language: "Pashto",
    ssn: "547-81-0366",
    money: "$399.38",
  },
  {
    fullName: "Eal Cluitt",
    gender: "Male",
    jobTitle: "Analyst Programmer",
    language: "Tsonga",
    ssn: "648-72-5376",
    money: "$747.60",
  },
  {
    fullName: "Andris Lamborne",
    gender: "Male",
    jobTitle: "Help Desk Technician",
    language: "Guaraní",
    ssn: "367-93-5134",
    money: "$73.60",
  },
  {
    fullName: "Kellie Staggs",
    gender: "Female",
    jobTitle: "Programmer II",
    language: "Icelandic",
    ssn: "867-52-5948",
    money: "$852.86",
  },
  {
    fullName: "Jehu Mansion",
    gender: "Male",
    jobTitle: "Operator",
    language: "Persian",
    ssn: "553-01-2747",
    money: "$986.93",
  },
  {
    fullName: "Claudell Vescovo",
    gender: "Male",
    jobTitle: "Senior Cost Accountant",
    language: "Aymara",
    ssn: "231-40-3005",
    money: "$15.66",
  },
  {
    fullName: "Lula Binford",
    gender: "Female",
    jobTitle: "Registered Nurse",
    language: "Latvian",
    ssn: "814-11-1139",
    money: "$991.78",
  },
  {
    fullName: "Chester Powelee",
    gender: "Male",
    jobTitle: "Social Worker",
    language: "Spanish",
    ssn: "650-83-1260",
    money: "$290.46",
  },
  {
    fullName: "Elwira Buten",
    gender: "Female",
    jobTitle: "Senior Financial Analyst",
    language: "Marathi",
    ssn: "476-63-7953",
    money: "$830.35",
  },
  {
    fullName: "Nisse Will",
    gender: "Female",
    jobTitle: "GIS Technical Architect",
    language: "Armenian",
    ssn: "494-57-1691",
    money: "$150.71",
  },
  {
    fullName: "Joseph Stanfield",
    gender: "Male",
    jobTitle: "Junior Executive",
    language: "Afrikaans",
    ssn: "265-82-5469",
    money: "$478.23",
  },
  {
    fullName: "Fitzgerald Mountfort",
    gender: "Male",
    jobTitle: "Assistant Professor",
    language: "Hiri Motu",
    ssn: "454-62-9576",
    money: "$316.26",
  },
  {
    fullName: "Chicky Aisbett",
    gender: "Male",
    jobTitle: "Design Engineer",
    language: "Hindi",
    ssn: "552-87-9146",
    money: "$924.60",
  },
  {
    fullName: "Barri Croote",
    gender: "Male",
    jobTitle: "Clinical Specialist",
    language: "Gagauz",
    ssn: "458-32-6006",
    money: "$139.03",
  },
  {
    fullName: "Patrizius Turpey",
    gender: "Male",
    jobTitle: "Compensation Analyst",
    language: "Dzongkha",
    ssn: "708-06-9695",
    money: "$29.55",
  },
  {
    fullName: "Franklin Heyburn",
    gender: "Male",
    jobTitle: "Quality Engineer",
    language: "Dzongkha",
    ssn: "479-55-1710",
    money: "$878.71",
  },
  {
    fullName: "David Keirl",
    gender: "Male",
    jobTitle: "Actuary",
    language: "Bengali",
    ssn: "580-82-7983",
    money: "$402.53",
  },
  {
    fullName: "Deedee Almey",
    gender: "Female",
    jobTitle: "Mechanical Systems Engineer",
    language: "Dzongkha",
    ssn: "355-79-2111",
    money: "$434.32",
  },
  {
    fullName: "Fayre Di Carlo",
    gender: "Female",
    jobTitle: "GIS Technical Architect",
    language: "Tok Pisin",
    ssn: "885-20-7158",
    money: "$496.12",
  },
  {
    fullName: "Joaquin Boak",
    gender: "Male",
    jobTitle: "Safety Technician I",
    language: "Malay",
    ssn: "144-83-0254",
    money: "$700.73",
  },
  {
    fullName: "See Keymer",
    gender: "Male",
    jobTitle: "Civil Engineer",
    language: "Hindi",
    ssn: "762-56-4518",
    money: "$918.66",
  },
  {
    fullName: "Noella Leroy",
    gender: "Female",
    jobTitle: "Recruiting Manager",
    language: "Montenegrin",
    ssn: "372-04-6695",
    money: "$100.75",
  },
  {
    fullName: "Marj Allsep",
    gender: "Female",
    jobTitle: "Librarian",
    language: "Kurdish",
    ssn: "307-79-3049",
    money: "$471.45",
  },
  {
    fullName: "Rozanne Fragino",
    gender: "Female",
    jobTitle: "Budget/Accounting Analyst II",
    language: "Swedish",
    ssn: "381-62-1786",
    money: "$452.49",
  },
  {
    fullName: "Waylin Skellion",
    gender: "Male",
    jobTitle: "Environmental Specialist",
    language: "Finnish",
    ssn: "434-59-8376",
    money: "$732.63",
  },
  {
    fullName: "Tansy Hartburn",
    gender: "Female",
    jobTitle: "Computer Systems Analyst IV",
    language: "Oriya",
    ssn: "690-86-6969",
    money: "$666.79",
  },
  {
    fullName: "Hubert Cornier",
    gender: "Male",
    jobTitle: "VP Marketing",
    language: "West Frisian",
    ssn: "835-35-8805",
    money: "$564.93",
  },
  {
    fullName: "Carr Maleney",
    gender: "Male",
    jobTitle: "Analog Circuit Design manager",
    language: "Croatian",
    ssn: "577-26-0660",
    money: "$888.84",
  },
  {
    fullName: "Lilian Renon",
    gender: "Female",
    jobTitle: "Account Executive",
    language: "Amharic",
    ssn: "787-76-6774",
    money: "$174.77",
  },
  {
    fullName: "Mar Longworthy",
    gender: "Male",
    jobTitle: "Business Systems Development Analyst",
    language: "Gagauz",
    ssn: "225-71-6271",
    money: "$590.31",
  },
  {
    fullName: "Nate Roz",
    gender: "Male",
    jobTitle: "VP Quality Control",
    language: "Ndebele",
    ssn: "575-61-5705",
    money: "$64.71",
  },
  {
    fullName: "Lou Freebury",
    gender: "Female",
    jobTitle: "Legal Assistant",
    language: "Yiddish",
    ssn: "821-68-1262",
    money: "$246.10",
  },
  {
    fullName: "Waldon Spedding",
    gender: "Male",
    jobTitle: "Chemical Engineer",
    language: "Lithuanian",
    ssn: "610-88-9163",
    money: "$35.37",
  },
  {
    fullName: "Rosalyn Bullar",
    gender: "Female",
    jobTitle: "Product Engineer",
    language: "Bislama",
    ssn: "172-87-3039",
    money: "$671.99",
  },
  {
    fullName: "Kevin Orrah",
    gender: "Male",
    jobTitle: "Financial Advisor",
    language: "Czech",
    ssn: "649-48-5245",
    money: "$359.74",
  },
  {
    fullName: "Cornell Megson",
    gender: "Male",
    jobTitle: "Programmer I",
    language: "Croatian",
    ssn: "646-86-3991",
    money: "$727.31",
  },
  {
    fullName: "Terri-jo Stoeckle",
    gender: "Female",
    jobTitle: "Physical Therapy Assistant",
    language: "Korean",
    ssn: "590-94-6035",
    money: "$82.48",
  },
  {
    fullName: "Florinda Hurlston",
    gender: "Female",
    jobTitle: "Recruiting Manager",
    language: "Amharic",
    ssn: "782-57-9102",
    money: "$743.73",
  },
  {
    fullName: "Winni McLelland",
    gender: "Female",
    jobTitle: "Dental Hygienist",
    language: "Guaraní",
    ssn: "797-22-6456",
    money: "$973.31",
  },
  {
    fullName: "Towny Melton",
    gender: "Male",
    jobTitle: "Account Coordinator",
    language: "Malay",
    ssn: "715-17-5594",
    money: "$268.39",
  },
  {
    fullName: "Mylo Tieraney",
    gender: "Male",
    jobTitle: "Nurse Practicioner",
    language: "Bosnian",
    ssn: "419-04-3652",
    money: "$67.84",
  },
  {
    fullName: "Theda Manuello",
    gender: "Female",
    jobTitle: "Dental Hygienist",
    language: "Malayalam",
    ssn: "186-56-9733",
    money: "$857.65",
  },
  {
    fullName: "Merwyn Rhodus",
    gender: "Male",
    jobTitle: "Web Developer I",
    language: "Greek",
    ssn: "192-40-5260",
    money: "$788.24",
  },
  {
    fullName: "Niko Otton",
    gender: "Male",
    jobTitle: "Junior Executive",
    language: "Greek",
    ssn: "862-27-8529",
    money: "$128.42",
  },
  {
    fullName: "Ludwig McNeilly",
    gender: "Male",
    jobTitle: "Safety Technician II",
    language: "Armenian",
    ssn: "100-60-4161",
    money: "$944.92",
  },
  {
    fullName: "Kendra Descroix",
    gender: "Female",
    jobTitle: "Teacher",
    language: "West Frisian",
    ssn: "707-78-4972",
    money: "$193.03",
  },
  {
    fullName: "Aldwin Goadbie",
    gender: "Male",
    jobTitle: "Computer Systems Analyst IV",
    language: "Irish Gaelic",
    ssn: "118-37-8372",
    money: "$222.67",
  },
  {
    fullName: "Chantal Casham",
    gender: "Female",
    jobTitle: "Staff Scientist",
    language: "Kashmiri",
    ssn: "283-12-2328",
    money: "$722.02",
  },
  {
    fullName: "Emmanuel Pavlasek",
    gender: "Male",
    jobTitle: "Statistician I",
    language: "Greek",
    ssn: "844-93-5795",
    money: "$47.46",
  },
  {
    fullName: "Cal Webby",
    gender: "Female",
    jobTitle: "Administrative Assistant II",
    language: "Punjabi",
    ssn: "275-33-6164",
    money: "$874.04",
  },
  {
    fullName: "Marsiella Aleksahkin",
    gender: "Female",
    jobTitle: "Programmer Analyst IV",
    language: "Bengali",
    ssn: "146-22-7768",
    money: "$763.27",
  },
  {
    fullName: "Silas Beebis",
    gender: "Male",
    jobTitle: "Editor",
    language: "Swedish",
    ssn: "743-45-1749",
    money: "$69.46",
  },
  {
    fullName: "Abby Austing",
    gender: "Female",
    jobTitle: "Health Coach I",
    language: "Māori",
    ssn: "548-11-6779",
    money: "$137.53",
  },
  {
    fullName: "Jolene Clemenzi",
    gender: "Female",
    jobTitle: "Nuclear Power Engineer",
    language: "Japanese",
    ssn: "869-06-9941",
    money: "$674.17",
  },
  {
    fullName: "Teddy Gonet",
    gender: "Female",
    jobTitle: "Financial Analyst",
    language: "Georgian",
    ssn: "256-28-9651",
    money: "$30.02",
  },
  {
    fullName: "Berenice Jewel",
    gender: "Female",
    jobTitle: "Associate Professor",
    language: "French",
    ssn: "558-20-6740",
    money: "$999.81",
  },
  {
    fullName: "Agnola Shimmings",
    gender: "Female",
    jobTitle: "Software Test Engineer I",
    language: "Hiri Motu",
    ssn: "593-89-6587",
    money: "$578.25",
  },
  {
    fullName: "Marilin Netherwood",
    gender: "Female",
    jobTitle: "Quality Engineer",
    language: "Malayalam",
    ssn: "892-30-7165",
    money: "$385.41",
  },
  {
    fullName: "Morie Wrixon",
    gender: "Male",
    jobTitle: "Chief Design Engineer",
    language: "Arabic",
    ssn: "663-32-0808",
    money: "$90.14",
  },
  {
    fullName: "Hernando Sime",
    gender: "Male",
    jobTitle: "Physical Therapy Assistant",
    language: "Danish",
    ssn: "210-97-8694",
    money: "$218.11",
  },
  {
    fullName: "Henriette Bloodworth",
    gender: "Female",
    jobTitle: "Senior Cost Accountant",
    language: "Arabic",
    ssn: "623-23-4118",
    money: "$87.47",
  },
  {
    fullName: "Olva Dungate",
    gender: "Female",
    jobTitle: "Health Coach IV",
    language: "Tswana",
    ssn: "311-59-1703",
    money: "$631.90",
  },
  {
    fullName: "Ilene Welbelove",
    gender: "Female",
    jobTitle: "Desktop Support Technician",
    language: "Portuguese",
    ssn: "362-11-0505",
    money: "$382.88",
  },
  {
    fullName: "Isidor Pien",
    gender: "Male",
    jobTitle: "Systems Administrator I",
    language: "Yiddish",
    ssn: "848-15-6547",
    money: "$542.18",
  },
  {
    fullName: "Mateo Kleinerman",
    gender: "Male",
    jobTitle: "VP Quality Control",
    language: "Haitian Creole",
    ssn: "646-19-3667",
    money: "$75.55",
  },
  {
    fullName: "Dian O'Reilly",
    gender: "Female",
    jobTitle: "Actuary",
    language: "Khmer",
    ssn: "114-39-0406",
    money: "$911.63",
  },
  {
    fullName: "Anselm Romushkin",
    gender: "Male",
    jobTitle: "Recruiting Manager",
    language: "New Zealand Sign Language",
    ssn: "632-67-9864",
    money: "$581.11",
  },
  {
    fullName: "Kenyon Glewe",
    gender: "Male",
    jobTitle: "Web Designer IV",
    language: "Malayalam",
    ssn: "755-03-5788",
    money: "$229.58",
  },
  {
    fullName: "Berri McFater",
    gender: "Female",
    jobTitle: "Account Executive",
    language: "Tswana",
    ssn: "639-67-0586",
    money: "$276.02",
  },
  {
    fullName: "Fons Sandeland",
    gender: "Male",
    jobTitle: "Social Worker",
    language: "German",
    ssn: "438-98-6161",
    money: "$946.97",
  },
  {
    fullName: "Kennan Londsdale",
    gender: "Male",
    jobTitle: "Account Representative IV",
    language: "Kyrgyz",
    ssn: "323-26-6494",
    money: "$485.24",
  },
  {
    fullName: "Mahala Alflatt",
    gender: "Female",
    jobTitle: "Web Developer III",
    language: "Fijian",
    ssn: "134-18-9308",
    money: "$243.44",
  },
  {
    fullName: "Blair Dawe",
    gender: "Male",
    jobTitle: "Occupational Therapist",
    language: "Irish Gaelic",
    ssn: "337-40-6723",
    money: "$978.08",
  },
  {
    fullName: "Karmen Gabbitis",
    gender: "Female",
    jobTitle: "Financial Analyst",
    language: "Punjabi",
    ssn: "120-59-4959",
    money: "$74.55",
  },
  {
    fullName: "Catherina Bowerman",
    gender: "Female",
    jobTitle: "Editor",
    language: "Kannada",
    ssn: "246-56-9792",
    money: "$451.01",
  },
  {
    fullName: "Norry Ridett",
    gender: "Male",
    jobTitle: "Senior Quality Engineer",
    language: "Tok Pisin",
    ssn: "378-23-0452",
    money: "$383.84",
  },
  {
    fullName: "Jami Gorler",
    gender: "Female",
    jobTitle: "Administrative Assistant I",
    language: "Zulu",
    ssn: "102-08-4681",
    money: "$379.82",
  },
  {
    fullName: "Ashbey Loud",
    gender: "Male",
    jobTitle: "Senior Cost Accountant",
    language: "Aymara",
    ssn: "143-67-8083",
    money: "$331.78",
  },
  {
    fullName: "Melvyn Theodore",
    gender: "Male",
    jobTitle: "Geological Engineer",
    language: "Arabic",
    ssn: "783-68-7765",
    money: "$180.27",
  },
  {
    fullName: "Vale Squibbs",
    gender: "Female",
    jobTitle: "Desktop Support Technician",
    language: "Arabic",
    ssn: "287-26-0424",
    money: "$300.52",
  },
  {
    fullName: "Antoni Bampforth",
    gender: "Male",
    jobTitle: "Compensation Analyst",
    language: "Tsonga",
    ssn: "813-67-6880",
    money: "$610.99",
  },
  {
    fullName: "Rosalinde Davydenko",
    gender: "Female",
    jobTitle: "Pharmacist",
    language: "Thai",
    ssn: "335-63-9784",
    money: "$416.98",
  },
  {
    fullName: "Edin Leist",
    gender: "Female",
    jobTitle: "Physical Therapy Assistant",
    language: "Korean",
    ssn: "834-08-1289",
    money: "$690.54",
  },
  {
    fullName: "Jeana Shovelton",
    gender: "Female",
    jobTitle: "Geological Engineer",
    language: "Kashmiri",
    ssn: "177-79-2175",
    money: "$449.45",
  },
  {
    fullName: "Obed Niche",
    gender: "Male",
    jobTitle: "Software Test Engineer I",
    language: "Kannada",
    ssn: "828-53-3136",
    money: "$136.92",
  },
  {
    fullName: "Aurelie Geke",
    gender: "Female",
    jobTitle: "VP Marketing",
    language: "Haitian Creole",
    ssn: "310-62-2360",
    money: "$934.00",
  },
  {
    fullName: "Mickie Culmer",
    gender: "Female",
    jobTitle: "Geological Engineer",
    language: "Norwegian",
    ssn: "377-03-6016",
    money: "$247.88",
  },
  {
    fullName: "Cybill Rapson",
    gender: "Female",
    jobTitle: "Librarian",
    language: "Greek",
    ssn: "843-32-4738",
    money: "$322.64",
  },
  {
    fullName: "Evangelina Gofton",
    gender: "Female",
    jobTitle: "Assistant Professor",
    language: "Papiamento",
    ssn: "640-38-0046",
    money: "$166.21",
  },
  {
    fullName: "Chalmers Kenion",
    gender: "Male",
    jobTitle: "Paralegal",
    language: "German",
    ssn: "653-38-5560",
    money: "$170.47",
  },
  {
    fullName: "Meggi Sporle",
    gender: "Female",
    jobTitle: "Staff Accountant III",
    language: "Filipino",
    ssn: "774-69-5721",
    money: "$421.68",
  },
  {
    fullName: "Debor Hinrich",
    gender: "Female",
    jobTitle: "Assistant Manager",
    language: "French",
    ssn: "292-49-7528",
    money: "$107.16",
  },
  {
    fullName: "Ric Voak",
    gender: "Male",
    jobTitle: "Environmental Specialist",
    language: "Papiamento",
    ssn: "223-82-8568",
    money: "$345.81",
  },
  {
    fullName: "Alejandro Sewards",
    gender: "Male",
    jobTitle: "Data Coordinator",
    language: "Guaraní",
    ssn: "344-50-9841",
    money: "$182.65",
  },
  {
    fullName: "Thurstan Garthside",
    gender: "Male",
    jobTitle: "Account Executive",
    language: "Afrikaans",
    ssn: "414-81-0157",
    money: "$851.16",
  },
  {
    fullName: "Shirline Musker",
    gender: "Female",
    jobTitle: "Marketing Assistant",
    language: "Guaraní",
    ssn: "791-79-7680",
    money: "$606.51",
  },
  {
    fullName: "Linoel Quarrie",
    gender: "Male",
    jobTitle: "Senior Cost Accountant",
    language: "Amharic",
    ssn: "517-97-5542",
    money: "$135.82",
  },
  {
    fullName: "Emelyne Eccleshall",
    gender: "Female",
    jobTitle: "Accountant IV",
    language: "Finnish",
    ssn: "684-02-7537",
    money: "$470.70",
  },
  {
    fullName: "Levin Kuhnhardt",
    gender: "Male",
    jobTitle: "GIS Technical Architect",
    language: "English",
    ssn: "240-86-8430",
    money: "$810.08",
  },
  {
    fullName: "Corine Philippe",
    gender: "Female",
    jobTitle: "Product Engineer",
    language: "Croatian",
    ssn: "365-15-8749",
    money: "$669.89",
  },
  {
    fullName: "Leandra Ginman",
    gender: "Female",
    jobTitle: "Registered Nurse",
    language: "Malayalam",
    ssn: "509-75-4354",
    money: "$117.27",
  },
  {
    fullName: "Tatiana Searston",
    gender: "Female",
    jobTitle: "Computer Systems Analyst III",
    language: "Macedonian",
    ssn: "190-55-3916",
    money: "$77.11",
  },
  {
    fullName: "Abelard Cahey",
    gender: "Male",
    jobTitle: "Marketing Manager",
    language: "Tsonga",
    ssn: "745-30-2112",
    money: "$669.88",
  },
  {
    fullName: "Ettore Longhorne",
    gender: "Male",
    jobTitle: "Systems Administrator II",
    language: "Malayalam",
    ssn: "133-59-1413",
    money: "$8.65",
  },
  {
    fullName: "Eli D'Andrea",
    gender: "Male",
    jobTitle: "Budget/Accounting Analyst I",
    language: "Icelandic",
    ssn: "650-13-4185",
    money: "$582.36",
  },
  {
    fullName: "Raimundo Toleman",
    gender: "Male",
    jobTitle: "Administrative Assistant I",
    language: "Pashto",
    ssn: "661-75-7284",
    money: "$569.17",
  },
  {
    fullName: "Ottilie Ison",
    gender: "Female",
    jobTitle: "Assistant Professor",
    language: "Papiamento",
    ssn: "211-06-9824",
    money: "$460.72",
  },
  {
    fullName: "Alina O'Kerin",
    gender: "Female",
    jobTitle: "Database Administrator III",
    language: "Icelandic",
    ssn: "788-39-5178",
    money: "$600.70",
  },
  {
    fullName: "Deck Tunesi",
    gender: "Male",
    jobTitle: "Community Outreach Specialist",
    language: "Dzongkha",
    ssn: "661-24-0146",
    money: "$162.84",
  },
  {
    fullName: "Pail Cumberland",
    gender: "Male",
    jobTitle: "Junior Executive",
    language: "Swati",
    ssn: "237-62-6050",
    money: "$116.47",
  },
  {
    fullName: "Clement Grimsley",
    gender: "Male",
    jobTitle: "Senior Quality Engineer",
    language: "Kyrgyz",
    ssn: "581-08-4203",
    money: "$167.00",
  },
  {
    fullName: "Denise Benardette",
    gender: "Female",
    jobTitle: "Clinical Specialist",
    language: "Finnish",
    ssn: "309-13-7682",
    money: "$727.94",
  },
  {
    fullName: "Myrah Matzke",
    gender: "Female",
    jobTitle: "Analog Circuit Design manager",
    language: "Hungarian",
    ssn: "441-05-0056",
    money: "$871.33",
  },
  {
    fullName: "Faye Pepis",
    gender: "Female",
    jobTitle: "Community Outreach Specialist",
    language: "West Frisian",
    ssn: "813-78-5812",
    money: "$775.20",
  },
  {
    fullName: "Roberto Ivetts",
    gender: "Male",
    jobTitle: "Information Systems Manager",
    language: "Fijian",
    ssn: "559-51-8509",
    money: "$302.63",
  },
  {
    fullName: "Noelle Brende",
    gender: "Female",
    jobTitle: "Executive Secretary",
    language: "Tsonga",
    ssn: "598-96-3186",
    money: "$669.50",
  },
  {
    fullName: "Urbain Ablitt",
    gender: "Male",
    jobTitle: "Senior Sales Associate",
    language: "Dutch",
    ssn: "599-72-6261",
    money: "$603.27",
  },
  {
    fullName: "Ameline Meyrick",
    gender: "Female",
    jobTitle: "VP Product Management",
    language: "Icelandic",
    ssn: "519-89-4899",
    money: "$79.43",
  },
  {
    fullName: "Rozella Kieran",
    gender: "Female",
    jobTitle: "Nurse Practicioner",
    language: "Moldovan",
    ssn: "690-29-7647",
    money: "$778.01",
  },
  {
    fullName: "Amby Ubee",
    gender: "Male",
    jobTitle: "Executive Secretary",
    language: "Georgian",
    ssn: "448-55-5164",
    money: "$983.10",
  },
  {
    fullName: "Erastus Stannard",
    gender: "Male",
    jobTitle: "Dental Hygienist",
    language: "Bulgarian",
    ssn: "375-74-2387",
    money: "$567.14",
  },
  {
    fullName: "Darnall Germain",
    gender: "Male",
    jobTitle: "Chief Design Engineer",
    language: "Khmer",
    ssn: "677-78-4307",
    money: "$398.71",
  },
  {
    fullName: "Joeann Perulli",
    gender: "Female",
    jobTitle: "Web Designer III",
    language: "Dari",
    ssn: "515-94-3024",
    money: "$398.34",
  },
  {
    fullName: "Antoine Hullbrook",
    gender: "Male",
    jobTitle: "Business Systems Development Analyst",
    language: "Ndebele",
    ssn: "879-34-4467",
    money: "$590.72",
  },
  {
    fullName: "Brant Lawtie",
    gender: "Male",
    jobTitle: "Recruiter",
    language: "Maltese",
    ssn: "851-14-7093",
    money: "$202.48",
  },
  {
    fullName: "Sonja Node",
    gender: "Female",
    jobTitle: "VP Sales",
    language: "Spanish",
    ssn: "141-94-1856",
    money: "$199.02",
  },
  {
    fullName: "Kipp Bohlje",
    gender: "Male",
    jobTitle: "Analyst Programmer",
    language: "Malagasy",
    ssn: "833-70-8068",
    money: "$522.45",
  },
  {
    fullName: "Renae Alcock",
    gender: "Female",
    jobTitle: "Community Outreach Specialist",
    language: "Dari",
    ssn: "172-65-2745",
    money: "$492.91",
  },
  {
    fullName: "Kristina Wardroper",
    gender: "Female",
    jobTitle: "Assistant Professor",
    language: "Zulu",
    ssn: "261-21-3041",
    money: "$944.87",
  },
  {
    fullName: "Husain Brouard",
    gender: "Male",
    jobTitle: "GIS Technical Architect",
    language: "Finnish",
    ssn: "840-26-3566",
    money: "$536.61",
  },
  {
    fullName: "Neron Smidmor",
    gender: "Male",
    jobTitle: "Mechanical Systems Engineer",
    language: "Hindi",
    ssn: "259-49-2489",
    money: "$511.22",
  },
  {
    fullName: "Effie Neville",
    gender: "Female",
    jobTitle: "Pharmacist",
    language: "Quechua",
    ssn: "621-61-7983",
    money: "$175.32",
  },
  {
    fullName: "Franz Ferrari",
    gender: "Male",
    jobTitle: "Accountant IV",
    language: "Malagasy",
    ssn: "624-30-3008",
    money: "$57.87",
  },
  {
    fullName: "Iolande Krug",
    gender: "Female",
    jobTitle: "Software Test Engineer I",
    language: "Hindi",
    ssn: "857-11-8522",
    money: "$308.16",
  },
  {
    fullName: "Nada Espley",
    gender: "Female",
    jobTitle: "Project Manager",
    language: "Portuguese",
    ssn: "569-60-8896",
    money: "$255.20",
  },
  {
    fullName: "Graeme Wiffler",
    gender: "Male",
    jobTitle: "Research Assistant IV",
    language: "Ndebele",
    ssn: "655-53-3150",
    money: "$683.82",
  },
  {
    fullName: "Sapphira Ashton",
    gender: "Female",
    jobTitle: "Database Administrator III",
    language: "Luxembourgish",
    ssn: "655-97-3863",
    money: "$902.81",
  },
  {
    fullName: "Bonny Grimsey",
    gender: "Female",
    jobTitle: "Graphic Designer",
    language: "Quechua",
    ssn: "876-43-8523",
    money: "$613.08",
  },
  {
    fullName: "Ole Harbison",
    gender: "Male",
    jobTitle: "Structural Engineer",
    language: "Nepali",
    ssn: "438-53-7018",
    money: "$578.24",
  },
  {
    fullName: "Roxie Sunnex",
    gender: "Female",
    jobTitle: "Structural Analysis Engineer",
    language: "English",
    ssn: "889-32-9409",
    money: "$759.72",
  },
  {
    fullName: "Harwell Pluvier",
    gender: "Male",
    jobTitle: "Analyst Programmer",
    language: "Latvian",
    ssn: "376-32-8982",
    money: "$669.61",
  },
  {
    fullName: "Nester Lansberry",
    gender: "Male",
    jobTitle: "GIS Technical Architect",
    language: "Armenian",
    ssn: "117-55-5416",
    money: "$938.32",
  },
  {
    fullName: "Fidelio Goudard",
    gender: "Male",
    jobTitle: "Biostatistician I",
    language: "Northern Sotho",
    ssn: "679-76-4720",
    money: "$289.87",
  },
  {
    fullName: "Maxwell Musk",
    gender: "Male",
    jobTitle: "Research Assistant II",
    language: "Kashmiri",
    ssn: "435-49-1260",
    money: "$361.48",
  },
  {
    fullName: "Niels Ruddle",
    gender: "Male",
    jobTitle: "Biostatistician II",
    language: "Northern Sotho",
    ssn: "525-25-8690",
    money: "$610.04",
  },
  {
    fullName: "Van Bend",
    gender: "Male",
    jobTitle: "Clinical Specialist",
    language: "Somali",
    ssn: "347-22-4973",
    money: "$223.23",
  },
  {
    fullName: "Bonny Gomme",
    gender: "Female",
    jobTitle: "Professor",
    language: "Papiamento",
    ssn: "733-61-2743",
    money: "$329.79",
  },
  {
    fullName: "Marcella Fraser",
    gender: "Female",
    jobTitle: "Nuclear Power Engineer",
    language: "Burmese",
    ssn: "648-64-7613",
    money: "$341.25",
  },
  {
    fullName: "Ody Hoyt",
    gender: "Male",
    jobTitle: "Administrative Assistant II",
    language: "Gagauz",
    ssn: "761-95-6899",
    money: "$779.41",
  },
  {
    fullName: "Jeanelle Taffley",
    gender: "Female",
    jobTitle: "Civil Engineer",
    language: "Armenian",
    ssn: "469-24-9342",
    money: "$292.84",
  },
  {
    fullName: "Joete Blyden",
    gender: "Female",
    jobTitle: "Analyst Programmer",
    language: "Korean",
    ssn: "365-66-6767",
    money: "$280.28",
  },
  {
    fullName: "Kevyn Massingham",
    gender: "Female",
    jobTitle: "Graphic Designer",
    language: "Oriya",
    ssn: "340-27-7208",
    money: "$51.12",
  },
  {
    fullName: "Mohandis Webland",
    gender: "Male",
    jobTitle: "Recruiting Manager",
    language: "Oriya",
    ssn: "884-34-1701",
    money: "$941.47",
  },
  {
    fullName: "Bobbi Heigold",
    gender: "Female",
    jobTitle: "Staff Accountant II",
    language: "Khmer",
    ssn: "833-09-1980",
    money: "$343.88",
  },
  {
    fullName: "Lilly Willes",
    gender: "Female",
    jobTitle: "Cost Accountant",
    language: "Burmese",
    ssn: "186-76-4788",
    money: "$126.36",
  },
  {
    fullName: "Muffin Fyall",
    gender: "Male",
    jobTitle: "Systems Administrator III",
    language: "Romanian",
    ssn: "718-52-5771",
    money: "$919.02",
  },
  {
    fullName: "Vladimir Kippins",
    gender: "Male",
    jobTitle: "Research Assistant I",
    language: "Polish",
    ssn: "398-28-8843",
    money: "$881.54",
  },
  {
    fullName: "Seward Saintsbury",
    gender: "Male",
    jobTitle: "Account Representative IV",
    language: "Marathi",
    ssn: "884-03-1049",
    money: "$760.14",
  },
  {
    fullName: "Leslie Pien",
    gender: "Male",
    jobTitle: "Cost Accountant",
    language: "West Frisian",
    ssn: "293-07-8505",
    money: "$795.96",
  },
  {
    fullName: "Roobbie Bunt",
    gender: "Female",
    jobTitle: "Quality Control Specialist",
    language: "Zulu",
    ssn: "682-77-5009",
    money: "$350.37",
  },
  {
    fullName: "Annissa Spearing",
    gender: "Female",
    jobTitle: "Graphic Designer",
    language: "Malay",
    ssn: "537-70-4850",
    money: "$523.75",
  },
  {
    fullName: "Adolph Musicka",
    gender: "Male",
    jobTitle: "Teacher",
    language: "Luxembourgish",
    ssn: "757-57-6723",
    money: "$208.21",
  },
  {
    fullName: "Carley MacGhee",
    gender: "Female",
    jobTitle: "Chief Design Engineer",
    language: "Dhivehi",
    ssn: "324-32-8751",
    money: "$440.50",
  },
  {
    fullName: "Renard Mordey",
    gender: "Male",
    jobTitle: "Environmental Specialist",
    language: "Tok Pisin",
    ssn: "784-90-4360",
    money: "$345.04",
  },
  {
    fullName: "Naoma Winham",
    gender: "Female",
    jobTitle: "Community Outreach Specialist",
    language: "Greek",
    ssn: "879-50-4050",
    money: "$20.35",
  },
  {
    fullName: "Batsheva Keir",
    gender: "Female",
    jobTitle: "Geologist IV",
    language: "Greek",
    ssn: "823-15-6281",
    money: "$152.21",
  },
  {
    fullName: "Rickert Farrington",
    gender: "Male",
    jobTitle: "Senior Sales Associate",
    language: "Danish",
    ssn: "220-49-0594",
    money: "$948.55",
  },
  {
    fullName: "Maddy Galvin",
    gender: "Male",
    jobTitle: "Civil Engineer",
    language: "Greek",
    ssn: "143-60-3695",
    money: "$423.99",
  },
  {
    fullName: "Hercule Stalf",
    gender: "Male",
    jobTitle: "Software Engineer IV",
    language: "Fijian",
    ssn: "614-83-2684",
    money: "$845.66",
  },
  {
    fullName: "Polly Ruilton",
    gender: "Female",
    jobTitle: "Nurse",
    language: "Spanish",
    ssn: "120-95-8156",
    money: "$675.85",
  },
  {
    fullName: "Steve Lusgdin",
    gender: "Male",
    jobTitle: "Nuclear Power Engineer",
    language: "Belarusian",
    ssn: "777-95-0715",
    money: "$422.49",
  },
  {
    fullName: "Addi Bolderstone",
    gender: "Female",
    jobTitle: "Software Engineer II",
    language: "Filipino",
    ssn: "718-43-2355",
    money: "$370.02",
  },
  {
    fullName: "Dame Pendleberry",
    gender: "Male",
    jobTitle: "Associate Professor",
    language: "Amharic",
    ssn: "398-44-7560",
    money: "$292.67",
  },
  {
    fullName: "Danya Plet",
    gender: "Male",
    jobTitle: "Statistician III",
    language: "Dzongkha",
    ssn: "499-65-3661",
    money: "$210.20",
  },
  {
    fullName: "Lin Pattingson",
    gender: "Female",
    jobTitle: "Internal Auditor",
    language: "Tamil",
    ssn: "890-96-8422",
    money: "$335.01",
  },
  {
    fullName: "Dorie Boyington",
    gender: "Male",
    jobTitle: "VP Accounting",
    language: "Gagauz",
    ssn: "230-26-4086",
    money: "$435.20",
  },
  {
    fullName: "Bobby Navarre",
    gender: "Female",
    jobTitle: "Structural Analysis Engineer",
    language: "Chinese",
    ssn: "793-91-8221",
    money: "$325.33",
  },
  {
    fullName: "Val Deveral",
    gender: "Male",
    jobTitle: "Programmer I",
    language: "Macedonian",
    ssn: "292-57-5927",
    money: "$16.45",
  },
  {
    fullName: "Rog Rummings",
    gender: "Male",
    jobTitle: "Automation Specialist II",
    language: "Romanian",
    ssn: "141-55-4945",
    money: "$614.55",
  },
  {
    fullName: "Chancey Hrishanok",
    gender: "Male",
    jobTitle: "Physical Therapy Assistant",
    language: "Croatian",
    ssn: "595-50-3964",
    money: "$365.61",
  },
  {
    fullName: "Horst Dosdale",
    gender: "Male",
    jobTitle: "Safety Technician I",
    language: "Bengali",
    ssn: "600-25-1477",
    money: "$487.11",
  },
  {
    fullName: "Trenna Nielson",
    gender: "Female",
    jobTitle: "Executive Secretary",
    language: "Thai",
    ssn: "343-69-9096",
    money: "$26.43",
  },
  {
    fullName: "Pen Sima",
    gender: "Female",
    jobTitle: "Human Resources Manager",
    language: "Luxembourgish",
    ssn: "328-51-3027",
    money: "$477.79",
  },
];

//1. 풀네임에서 A,B,C로 시작하는 사람들만 남기기!
const q1 = data.filter(
  (x) =>
    x.fullName.startsWith("A") ||
    x.fullName.startsWith("B") ||
    x.fullName.startsWith("C")
);

console.log(q1);

//2. 성별이 여성이고, 풀네임이 10글자 이상인 사람만 남기기!

const q2 = data.filter((x) => x.gender == "Female" && x.fullName.length >= 10);

console.log(q2);

//3. 직업이 Manager인 사람만 남기고, 풀네임을 이름만 남기기!

const q3 = data
  .filter((x) => x.jobTitle.includes("Manager"))
  .map((x) => {
    x.fullName = x.fullName.split(" ")[0];
    return x;
  });

console.log(q3);
